### ISSUE TITLE
HTTP Basic Auth passed to MPV

### ISSUE THREAD

**Issue by mission712** [woodruffw/ff2mpv#10]
MPV recognizes HTTP basic auth logins in the form of `mpv http://user:pass@example.com/path/to/movie.mp4`

However, this plugin currently doesn't pass HTTP basic auth information when "Play with MPV" is clicked on a domain that needs it.

Is there a way to possibly include this? Does Firefox disallow getting the HTTP Basic Auth password for the domain? I'm fine with setting a per-domain setting on the addon page.

**Comment by woodruffw** [comment]
> Is there a way to possibly include this?

You can do this on the native client side, by fiddling with the `url` before passing it to `mpv`. In Ruby pseudocode:

```ruby
if URI(url).hostname == "example.com"
  url = add_auth url
end

pid = spawn "mpv", "--no-terminal", "--", url, in: :close, out: :close, err: :close
```

(or equivalently for the Python client).

This is probably how ff2mpv will "support" basic auth (and other kinds of URL fiddling) for the forseeable future.

**Comment by woodruffw** [comment]
Added https://github.com/woodruffw/ff2mpv/wiki/Custom-URL-behavior for people to reference.
