### ISSUE TITLE
Help with firefox snap installation

### ISSUE THREAD

**Issue by Lovecraft-github** [woodruffw/ff2mpv#100]
I can't make it works in my firefox snap installation.

I installed the extension from https://addons.mozilla.org/eu/firefox/addon/ff2mpv/
I downloaded the native client and installed it folowing https://github.com/woodruffw/ff2mpv/issues/80

I put the ff2mpv.json in /home/user/snap/firefox/common/.mozilla/native-messaging-hosts
and ff2mpv.py in /home/user/snap/firefox/common/.mozilla/native-messaging-hosts/ff2mpv
I made it executable and modified the path in the json like that

{
    "name": "ff2mpv",
    "description": "ff2mpv's external manifest",
    "path": "/home/user/snap/firefox/common/.mozilla/native-messaging-hosts/ff2mpv/ff2mpv.py",
    "type": "stdio",
    "allowed_extensions": ["ff2mpv@yossarian.net"]
}

flatpak permissions webextensions looks like that

`Tabla                      Objeto                                                                     Aplicación                     Permisos                 Datos

webextensions      ff2mpv                                                                    snap.firefox                  yes                           0x00

webextensions      org.gnome.chrome_gnome_shell                     snap.firefox                  yes                           0x00

webextensions      org.gnome.shell.extensions.gsconnect           snap.firefox                  yes                           0x00

MOZ_LOG=NativeMessagingPortal:5 firefox gives me this when I tried to use the menu or the toolbar button

[Parent 45241: Main Thread]: D/NativeMessagingPortal creating session with handle suffix firefox_ff2mpv_1565032335
[Parent 45241: Main Thread]: D/NativeMessagingPortal session created with handle /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335
[Parent 45241: Main Thread]: D/NativeMessagingPortal starting ff2mpv, requested by ff2mpv@yossarian.net in session /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335
[Parent 45241: Main Thread]: D/NativeMessagingPortal native application start requested in session /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335, pending response for /org/freedesktop/portal/desktop/request/1_268/firefox/1075319863
[Parent 45241: Main Thread]: D/NativeMessagingPortal got response signal for /org/freedesktop/portal/desktop/request/1_268/firefox/1075319863 in session /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335
[Parent 45241: Main Thread]: D/NativeMessagingPortal native application start failed in session /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335
[Parent 45241: Main Thread]: D/NativeMessagingPortal session /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335 was closed by the portal
[Parent 45241: Main Thread]: D/NativeMessagingPortal cannot close session /org/freedesktop/portal/desktop/session/1_268/firefox_ff2mpv_1565032335, unknown handle

## Platform information

 - OS information: Ubuntu 23.04
 - Firefox version: 115.0b6 (64-bit) Firefox snap for Ubuntu canonical-002-1.0
 - MPV version mpv 0.35.1
 - youtube-dl version yt-dlp 2023.03.04

**Comment by woodruffw** [comment]
See https://github.com/woodruffw/ff2mpv/issues/87 for possible solutions.

As mentioned in that thread: there are a bunch of interacting pieces and user configuration here, all of which is outside of this extension's control. If you find something that works for you, please add it to the wiki.

**Comment by GoodGuyNick** [comment]
I was able to have a dirty fix by downloading the latest Firefox from https://ftp.mozilla.org/pub/firefox/releases/, then launching it so that it will create `~/.mozilla` and after that installing `./install.sh firefox`.
