### ISSUE TITLE
Firefox 60: Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by ketetefid** [woodruffw/ff2mpv#11]
Mpv does not load with the latest firefox and your addon. Could you look into that?

This is the relevant part:
JavaScript error: moz-extension://28dfa88f-a733-40b7-911e-9313bd63c00e/ff2mpv.js, line 2: Error: Attempt to postMessage on disconnected port

**Comment by woodruffw** [comment]
I'm unable to replicate this on Firefox 61.0b4 on Linux. Make sure that you're using the latest version of the native client and have installed the manifest correctly.

If you've done all of that and still experience the error, please send me the following:

* Your operating system (`uname -srvo`)
* Any other debugging/error messages you see, if any, when you try to play a URL

**Comment by ketetefid** [comment]
Thanks for the reply.
I refreshed firefox with only your addon enabled. This is the log from running firefox in a terminal:

1526263223555	addons.webextension.ff2mpv@yossarian.net	WARN	Please specify whether you want browser_style or not in your browser_action options.

###!!! [Parent][DispatchAsyncMessage] Error: PClientSourceOp::Msg___delete__ Route error: message sent to unknown actor ID


###!!! [Parent][DispatchAsyncMessage] Error: PClientSourceOp::Msg___delete__ Route error: message sent to unknown actor ID

JavaScript error: moz-extension://973e53db-47a8-412b-9906-7c01746c47ac/ff2mpv.js, line 2: Error: Attempt to postMessage on disconnected port


#uname -srvo
Linux 4.16.8-gentoo #2 SMP PREEMPT Thu May 10 19:53:23 +0430 2018 GNU/Linux

**Comment by ketetefid** [comment]
My apologies. I was not aware that I had to complete the setup with further steps.

Following the installation steps, it worked perfectly.

**Comment by woodruffw** [comment]
Yeah, the new native extension apps are a bit of a pain to get set up. Glad to hear it's working now!
