### ISSUE TITLE
Hide dropdown with no profiles set

### ISSUE THREAD

**Issue by Velocidensity** [woodruffw/ff2mpv#114]
**Is your feature request related to a problem? Please describe.**
The new addition of profiles breaks my usual workflow of right clicking a link, and hitting "play in MPV", as the option is now hidden behind a dropdown, which takes a moment to open, and requires more movement. Additionally, the position of the ff2mpv entry in the context menu has changed.

**Describe the solution you'd like**
Dropdown should not be present when no profiles are set, and should show just "play in MPV". Alternatively, add an option to always enable a button alongside the dropdown.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by woodruffw** [comment]
> Dropdown should not be present when no profiles are set, and should show just "play in MPV". 
> Alternatively, add an option to always enable a button alongside the dropdown.

IIRC, the former idea isn't possible with context menus in WebExtensions (but I could be misremembering). OTOH, the latter idea should work; I'd be happy to accept a PR for it.

CC @DanSM-5 as well, in case you have any ideas. If nobody wants to do a PR here, I'll look into this when I have the free time.

**Comment by DanSM-5** [comment]
I think the first idea is possible by just changing the contents of the context menu. This depends if a profile is present or not, so it should be just checking if there are elements stored.

I can have something done tonight.

**Comment by woodruffw** [comment]
Done with #115. I'm going to do some cleanup and cut a minor release for this in a bit.

**Comment by woodruffw** [comment]
This has been released with 5.1.0, which is now available on AMO and will be available via the Chrome Store shortly. Thanks to all who reported, and thanks @DanSM-5 for the fix!

**Comment by juippis** [comment]
Hey,

on 5.1.0 I don't have the "Play in MPV" option in my right click menu at all now. Using Firefox. Downgrading to 4.0.0 still works.

**Comment by woodruffw** [comment]
> on 5.1.0 I don't have the "Play in MPV" option in my right click menu at all now. Using Firefox. Downgrading to 4.0.0 still works.

Hmm -- could you share your browser/OS/profile information? I confirmed that 5.1.0 reverts to the 4.x behavior locally, but there may be regressions.

**Comment by woodruffw** [comment]
> I'll open a new issue for visibility, if I'm not the only one out there :)

Thank you!
