### ISSUE TITLE
No "Play in MPV" option visible anymore in right click context menu after updating to 5.1.0

### ISSUE THREAD

**Issue by juippis** [woodruffw/ff2mpv#116]
**IMPORTANT: Please fill out every section below. Bug reports with missing information will be
given a lower priority or closed outright.**

## Describe the bug

After an update to 5.1.0 I don't see the option to "Play in MPV" in right click context menu anymore. Downgrading back to 4.0.0 brings the option back again. With 5.0.0 the option was there, but behind "Profiles" submenu.

## Reproduction steps

1. Go to e.g. youtube.
2. Right-click anywhere, right-click a video link.
3. "Play in MPV" missing in right click context menu.

## Expected behavior

The right click context menu should show "Play in MPV" option. At least is used to show in previous versions.

## Platform information

 - OS information: Gentoo Linux
 - Firefox version: 115.7.0 (115esr)
 - MPV version: 0.37.0
 - youtube-dl version: 2023.12.30 (yt-dlp)

## Additional context (optional)

I've done a manual installation - e.g. wgetting **ff2mpv.py** and editing the path in *~/.mozilla/native-messaging-hosts/ff2mpv.json*. Previous versions still work. Clicking the MPV icon on toolbar still plays the videos, so the addon is talking with native-messaging-host and my MPV just fine.

**Comment by DanSM-5** [comment]
Do you get any error in the console?

**Comment by juippis** [comment]
Unfortunately nothing obvious, but I may be doing it wrongly. Inspect -> Console, or Debugger. Or via `about:debugging` -> Inspect, where the same console appears.

**Comment by DanSM-5** [comment]
In this particular case the right console to look at is in **about: debugging** and click in the inspect button for ff2mpm.

The only reason I can imagine for getting neither "Play in MPV" nor "Profiles" context menu entries is for the ff2mpv.js script to error when loading.

**Comment by woodruffw** [comment]
#118 is a prospective fix here. I'll try to remember to do a release for this in the next few days, but please also try it locally!

**Comment by woodruffw** [comment]
Sure, no problem. I should have time to make that release tonight.

(Please don't hesitate to bug me ever if I forget this -- I regularly forget to make releases here, and I appreciate the reminders.)

**Comment by woodruffw** [comment]
I've cut v5.1.1 with this; it'll be available on AMO and Chrome Store shortly.

**Comment by juippis** [comment]
And I can confirm that I have the menu item back and it works! Thank you both!
