### ISSUE TITLE
Can't make it work yet on my new rig (console info attached)

### ISSUE THREAD

**Issue by JoseHidalgo** [woodruffw/ff2mpv#117]
Hi guys. Happy ff2mpv user here. :)
ff2mpv works perfectly on my old Win 7 rig, on both Firefox and Brave Browser.
So normally I should be able to install it properly on my new Win 11 rig.

Unfortunately I'm running into some issues which probably are my fault.
I have followed the instructions as best as I could, but it still doesn't work.

## Installation issue (solved)

FYI during the Firefox installation process (`.\install.ps1 firefox`), I got this error on PowerShell:
**** WARNING: mpv was not found!!! ****
Make sure it is installed and in your path to use the extension!!!
So I added `C:\Program Files\MPV` (which is where my mpv.exe is located) to my two `Path` variables.

![v1](https://github.com/woodruffw/ff2mpv/assets/10851603/5908e8f7-5dd5-46c3-b056-d61f2045681b)

![v2](https://github.com/woodruffw/ff2mpv/assets/10851603/cda3cc8c-e2f2-49d6-8c60-7d4d9995910e)

But that doesn't seem to have worked, because during the Brave installation process (`.\install.ps1 brave`) I got the same exact error...

## Problem description

Clicking on the ff2mpv button doesn't have any apparent effect, on both Firefox and Brave Browser.
Streaming a YT video via the console works perfectly (e.g. `mpv.exe [YT URL] --profile=youtube`).

Here's what Firefox console is showing:

![Console 2024-01-31 183730](https://github.com/woodruffw/ff2mpv/assets/10851603/e2f1d86d-76ce-4860-9a13-5746ff8b4283)

I guess if I manage to solve the issue for Firefox, I'll be able to solve it for Brave Browser as well.
Thanks in advance for your help!

## Platform information

 - OS information: Win 11 23H2
 - Firefox version: 88.0.1
 - MPV version: latest
 - yt-dlp version: latest

**Comment by woodruffw** [comment]
Thanks for the detailed report! I'm still not the best person to triage these, but I'll tag appropriately.

**Comment by DanSM-5** [comment]
It looks like mpv is still not found. Sometimes the environment isn't updated until you have a terminal open e.g. windows terminal. Try closing all terminal windows that you may have open, then open one (poweshell/cmd) and type `where.exe mpv`. If that returns the path `C:\Program Files\MPV\mpv.exe` then you are good.

**Comment by JoseHidalgo** [comment]
PROBLEM SOLVED!

Indeed MPV was still not found. A reboot did the trick. After the reboot, the terminal returned the correct path, and ff2mpv started working without any apparent issues, on both Brave and Firefox.

Thanks to both of you, and congrats again for this most excellent piece of software. It's amazing, really. :)
