### ISSUE TITLE
[Question] How to uninstall/remove the script

### ISSUE THREAD

**Issue by brxoo** [woodruffw/ff2mpv#120]
Hi, I started using the extension/script recently. And everything is working perfectly (thanks for that). But I have a simple question: if I no longer want to use the extension/script, how do I remove the script from my system? I installed the Linux script in the recommended way by cloning the repository. So, for me to remove the script, I would only need to delete the repository folder that I cloned?

**Comment by woodruffw** [comment]
> So, for me to remove the script, I would only need to delete the repository folder that I cloned?

Yes: uninstall the extension, and delete the script (or the whole repo). You might also need to manually delete the `ff2mpv.json` manifest from wherever you put it for your browser's native messaging functionality.

**Comment by brxoo** [comment]
> > So, for me to remove the script, I would only need to delete the repository folder that I cloned?
> 
> Yes: uninstall the extension, and delete the script (or the whole repo). You might also need to manually delete the `ff2mpv.json` manifest from wherever you put it for your browser's native messaging functionality.

Okay, I got it. Thank you very much.
