### ISSUE TITLE
Argument syntax

### ISSUE THREAD

**Issue by Targan822** [woodruffw/ff2mpv#121]
Hi, thanks for you extension, it works on Firefox with Arch Linux and MPV, but, I can't find what is attended in the argument section, I'd like to have maximum 1080p on MPV with FF2MPV. It launch the video with the maximum quality witch is too much for my laptop.

Thanks in advance.

**Comment by DanSM-5** [comment]
Setting the resolution is something you need to do in mpv.conf. This will make the change for all videos that mpv plays using yt-dlp:

```config
# ~/.config/mpv
ytdl-format="bestvideo[height<=1080][vcodec!=vp9]+bestaudio/best"
```

Optionally, if you wish to enable that for ff2mpv only, you could set the flag as a profile in ff2mpv. Go to extensions, find ff2mpv, extension options. There add a new profile with some name like "1080P" and add the argument for mpv:

```bash
--ytdl-format=bestvideo[height<=1080][vcodec!=vp9]+bestaudio/best
```
Save the profile and now you should get a new context menu entry with the "1080P" name which will forward the flag to mpv.
