### ISSUE TITLE
Video and/or audio freezing and never resuming on some YouTube videos

### ISSUE THREAD

**Issue by JoseHidalgo** [woodruffw/ff2mpv#127]
## Describe the bug

Hi. Recently on some YouTube videos played via ff2mpv, after a while (can be 3 min, 10 min, 15 min), the video just stops playing, but the audio keeps playing while the video remains in a frozen state (still image).

The same can happen if I want to skip a part of the video and go directly to another part (by clicking on MPV's time bar). Normally there would be some buffering and then everything would resume after a few seconds. But in this case the buffering never ends, or if it does, only the audio resumes, not the video.

Closing the video and playing it again with ff2mpv results in the same behaviour.

**Playing the video directly on YouTube results in no issues at all.**

I didn't have this issue a few weeks ago. So maybe YouTube has changed something which results in worse compatibility with ff2mpv? Or maybe it was due to me updating MPV to its latest version?

Also, this issue seems to happen with only some YouTube videos. Others just play normally. I just can't figure what's going on. All I know is that a few weeks ago, AFAIK 100% of the videos used to play normally.

## Reproduction steps

Here's an example of such YouTube videos: https://www.youtube.com/watch?v=BH45hWntkq4
Feel free to try and see if everything plays normally on your side.

## Screenshots (optional)

This is a screenshot taking during the issue. I tried to skip a part of the video by clicking on 6 min or so on MPV's time bar. The audio resumed eventually, but the video remained frozen at the last frame BEFORE I clicked on MPV's time bar (so, at the beginning of the video).

![2024 08 03 - 13 42 29](https://github.com/user-attachments/assets/905f45b1-f68e-41a6-af98-544c7fa8b466)

## Other information

Here's my [youtube] profile from mpv.conf, which used to work perfectly until recently:

```
[youtube]
ytdl-format="bestvideo[height<=?1440]+bestaudio/best"
ytdl-raw-options=ignore-config=,sub-lang="^en.*",write-sub=,write-auto-sub=

```
## Platform information

 OS information: Windows 11
 Firefox version: latest
 Brave version: latest (the problem happens in both navigators)
 MPV version: 

- mpv v0.38.0-633-ge509ec0a Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
-  built on Jul 20 2024 00:06:50
- libplacebo version: v7.349.0 (v7.349.0-dirty)
- FFmpeg version: N-116344-g5c8523cef
- FFmpeg library versions:
-    libavcodec      61.10.100
-    libavdevice     61.2.100
-    libavfilter     10.2.102
-    libavformat     61.5.101
-    libavutil       59.28.100
-    libswresample   5.2.100
-    libswscale      8.2.100

yt-dlp version: 2024-07-16

Thanks in advance! :)

**Comment by woodruffw** [comment]
Thanks for the report @JoseHidalgo, but I'm not sure this is an issue within the extension itself: all ff2mpv does is forward the URL to `mpv`, which then invokes `yt-dlp` or `youtube-dl` internally to handle it. If the video starts successfully but has problems in the *middle* of the stream, that strongly suggests that either `mpv` or `yt-dlp` has a bug that should be filed with one of those projects.

> yt-dlp version: 2024-07-16

You might want to try upgrading this and seeing if the issue persists: I just checked, and the latest version is 2024.8.1, which (from their issue tracker) seems to have a few fixes for YouTube streams.

I just tried playing the URL you provided with that version and it buffered to 100% immediately, without any problems during forward or backward seeking. Screencap below:

![](https://thing-in-itself.net/u/XbTkhCHylJs.png)
