### ISSUE TITLE
MPV doesn't open; An unexpected error occurred - Workaround

### ISSUE THREAD

**Issue by czarek7711** [woodruffw/ff2mpv#128]
Hello,

While trying to get the app running in Windows I run into an issue, where clicking 'Play in MPV' while watching a YouTube video wouldn't start the player, and 'An unexpected error occurred' would be logged in console.

By debugging the Firefox extension and Python script I discovered the issue was very similar to the one described here - https://stackoverflow.com/questions/36324/the-system-cannot-find-the-file-specified-when-invoking-subprocess-popen-in-py.

Traceback:

> 2024-09-15 01:16:59,412 ERROR __main__ Traceback (most recent call last):
  File "C:\Apps\ff2mpv\ff2mpv.py", line 56, in main
    subprocess.Popen(["mpv", "--no-terminal", "--", url], **kwargs)
  File "C:\Apps\Python\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Apps\Python\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

The solution described there did not help in my case.

What did help however, was calling both mpv and yt-dlp from their direct paths, not using the PATH environment variable.

I edited the python script - replaced "mpv" in args variable with "C:\\path\\to\\my\\mpv.exe" and provided the option "--script-opts=ytdl_hook-ytdl_path=C:\path\to\my\yt-dlp.exe"

I installed the app by following "Installation on Windows" directions.

I haven't tried other OS or Python versions.

I'm aware Windows support is limited, but at the very least I'm hoping people having similar issues find this report helpful.

## Platform information

 - OS information: Windows 10 (10.0.19045)
 - Firefox version: 129.0.2
 - MPV version:  v0.38.0-759-g5357d18f
 - yt-dlp version: 2024.08.06
 - Python version: 3.12.4

**Comment by woodruffw** [comment]
Thanks @czarek7711 -- could you put this in the wiki? That's where we typically put these kinds of debugging tips.

**Comment by czarek7711** [comment]
I'm personally fine with it being just here - so long as it's discoverable.

Feel free to link to it in the wiki, or however else you'd like this topic to be covered in there.

**Comment by woodruffw** [comment]
https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows#troubleshooting

**Comment by leftcausedit** [comment]
Try reboot, perhaps it's because python cached PATH and didn't refresh.
