### ISSUE TITLE
Context menu entry is gone on Firefox

### ISSUE THREAD

**Issue by Velocidensity** [woodruffw/ff2mpv#130]
## Describe the bug

"Play in mpv" context menu entry is gone, seemingly after the recent update.

## Platform information

 - OS information: Windows 10
 - Firefox version: 133.0
 - mpv version: 0.39.0
 - youtube-dl version: yt-dlp 2024.11.18

## Additional context (optional)

Only observed in the last couple of days, presumably after the latest update.

There is nothing relating to it in page, browser and about:debugging extension dev tools consoles that I can see.

The extension button still works as expected.

**Comment by woodruffw** [comment]
Thanks for the report @Velocidensity! I'll try and triage this tonight.

**Comment by DanSM-5** [comment]
I have tested on a windows 10 pc with firefox 133.0 and I was unable to reproduce. The context menu button is showing.

I wonder if the issue could be related to updates only. Could you try reinstalling the extension (just the browser extension, no need to setup the backend)?

**Comment by zedzad14** [comment]
I've also got this bug. Reinstalling the extension brought "Play in mpv" back.

**Comment by woodruffw** [comment]
Thanks all. I forgot to respond earlier, but I tried reproducing this last week and came to the same conclusion as @DanSM-5: if you're seeing this, try reinstalling. 

(I strongly suspect this is caused by the MV2 -> MV3 move, and browsers not respecting/preserving context menu defaults between the two.)

**Comment by Velocidensity** [comment]
Reinstalling restored it for me, thanks. Is there a way to reorder the context menu, by the way?

**Comment by woodruffw** [comment]
> Reinstalling restored it for me, thanks. Is there a way to reorder the context menu, by the way?

I think that's defined only on the browser's side. On Firefox there's probably something in the `about:config` for that, but I don't know it off the top of my head.
