### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by 07416** [woodruffw/ff2mpv#16]
Is there any hotkey functionality?

**Comment by woodruffw** [comment]
Yes. By default, Ctrl+Shift+V will try to play the current tab's URL in MPV.

**Comment by woodruffw** [comment]
Ref #14, which changed it in https://github.com/woodruffw/ff2mpv/commit/acc5b959f20b6ef26a4c6350b01efb7cea218c0e.

**Comment by rwmpelstilzchen** [comment]
Thank you. Is this documented anywhere?

**Comment by woodruffw** [comment]
Nope. Feel free to add a "User's Guide" page to the Wiki (attached to this repo) with any tips that you find helpful.
