### ISSUE TITLE
Should allow setting PATH when calling mpv

### ISSUE THREAD

**Issue by tpikonen** [woodruffw/ff2mpv#22]
My Linux Firefox runs without the standard PATH set (it's usually started from a launcher which does not source the shell variables). Since mpv often needs to call  other binaries (like youtube-dl), it fails in this case.

I fixed this in the Python script by calling Popen with shell=True and defining the PATH in the args, like this:

```
diff --git a/ff2mpv.py b/ff2mpv.py
index 67ba863..bd12d57 100755
--- a/ff2mpv.py
+++ b/ff2mpv.py
@@ -7,10 +7,12 @@ from subprocess import Popen, DEVNULL
 
 
 def main():
+    shpath = "PATH=/home/tpikonen/bin:/usr/bin"
     message = get_message()
     url = message.get("url")
     args = ["mpv", "--no-terminal", "--", url]
-    Popen(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)
+    shargs = " ".join([shpath] + args)
+    Popen(shargs, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL, shell=True)
     # Need to respond something to avoid "Error: An unexpected error occurred"
     # in Browser Console.
     send_message("ok")
```

There are probably cleaner ways to set the environment and it would be nice to read the PATH automatically from somewhere, but I'll let someone else make a better fix.

**Comment by woodruffw** [comment]
You should be **very** careful with this patch -- adding `shell=True` makes it trivial to perform a command injection with a crafted URL!

If you want to update your environment, you can use the `env` kwarg on the `Popen` constructor:

```python
Popen(args, env={"PATH": "whatever"}, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)
```
