### ISSUE TITLE
Error: Extension not responding despite successful Windows 10 installation

### ISSUE THREAD

**Issue by Neidkaris** [woodruffw/ff2mpv#26]
Good evening, friends.
I have followed the installation instructions as outlined in the installation guide, including verifying all necessary software as being installed and present in my computer. The registry key has been created as per the provided instructions, and checking the installation as instructed through the Windows Command Prompt provides a positive response, as follows:

Microsoft Windows [versão 10.0.17763.55]
(c) 2018 Microsoft Corporation. Todos os direitos reservados.

C:\Windows\system32>python check-config-win.py
python: can't open file 'check-config-win.py': [Errno 2] No such file or directory

C:\Windows\system32>cd C:\Misc\mpvbrowserintegration\ff2mpv

C:\Misc\mpvbrowserintegration\ff2mpv>python check-config-win.py
Checking: HKEY_CURRENT_USER Software\Mozilla\NativeMessagingHosts\ff2mpv
Path from registry key is: C:\Misc\mpvbrowserintegration\ff2mpv\ff2mpv-windows.json
Path from JSON is: ff2mpv.bat
Path from batch file is: ff2mpv.py
Looks good! Give it a try from Firefox.

C:\Misc\mpvbrowserintegration\ff2mpv>

However,  upon attempting to use the addon through the browser icon, I get no response. I would be grateful for any assistance in figuring out what I may have done wrong along the way and correcting it. Thank you in advance!

**Comment by woodruffw** [comment]
Pinging @thomastay, since you recently added Windows support. Any thoughts?

**Comment by thomastay** [comment]
Hey, @Neidkaris 
I have no idea of the exact details, but I can offer some advice:

1. Try rebooting the computer. This sounds really cliche but it has worked wonders for me in the past...
1. Check that the versions of Python, mpv match those in the instructions
1. Check that youtube-dl is installed.
1. Check that your firefox is the latest version
1. Navigate to the ff2mpv folder, and from a command prompt try running the batch file directly. That is, run `.\ff2mpv.bat`. Here's what I see: upon running, the console waits for you to enter input. Upon typing anything and hitting <Enter>, you should see a Python error. If you don't see what I see, then there's something wrong.

Outside of that, I'm not sure of what's wrong. If I have some time, I might try adding a logging feature to the python script, but I don't have the time right now. To whoever's interested, you could try making a temp directory using `tempfile` and log output to it using the  `logging` module.

```
~\ff2mpv>.\ff2mpv.bat
asd
Traceback (most recent call last):
  File "ff2mpv.py", line 38, in <module>
    main()
  File "ff2mpv.py", line 10, in main
    message = get_message()
  File "ff2mpv.py", line 25, in get_message
    message = sys.stdin.buffer.read(length).decode("utf-8")
ValueError: cannot read more than 33554432 bytes
```

**Comment by Neidkaris** [comment]
@thomastay Apologies, friend, I have gone down every single one of the items on the list, and no results have been yielded. My python installation is version 3.8.3. while the recommended version in the instructions is 3.8, youtube-dl is present, firefox is up to date as of the time of this post, and running ff2mpv.bat directly has yielded the same idleness and subsequent python error as expected.

Apologies for trying to offer what is essentially a random guess from someone with no real experience in this, but could it have anything to do with the contents of the json file and bat files? The json file in particular has this line in it

    "path": "/home/william/scripts/ff2mpv",

which for all I know might simply be related to the way firefox/the extension itself handles things internally, but if it is supposed to be referencing a physical path in my system, is not really pointing anywhere.

**Comment by woodruffw** [comment]
> Apologies for trying to offer what is essentially a random guess from someone with no real experience in this, but could it have anything to do with the contents of the json file and bat files? The json file in particular has this line in it
> 
> ```
> "path": "/home/william/scripts/ff2mpv",
> ```
> 
> which for all I know might simply be related to the way firefox/the extension itself handles things internally, but if it is supposed to be referencing a physical path in my system, is not really pointing anywhere.

Yes, this looks like the issue! Great guess.

That path needs to be updated to whereever you saved the `.bat` file.

The Linux and macOS pages document that change, but it looks like the Windows one doesn't currently. That needs to be fixed.

**Comment by woodruffw** [comment]
Ah, to be more clear: make sure that you're using the `ff2mpv-windows.json` file, not just `ff2mpv.json`. The `ff2mpv.json` file is for Linux and macOS only.

**Comment by Neidkaris** [comment]
@woodruffw Thank you, friend. I have followed the instructions, and while  it still has not resolved the issue, it seems to be on the right path, at least. After updating the file path on both the ff2mpv and ff2mpv-windows json files [and rebooting Windows again just to be sure] it still has no effect, however. For reference, the full contents of both the windows file and the .bat as of now are as follows

{
    "name": "ff2mpv",
    "description": "ff2mpv's native manifest",
    "path": "C:\Misc\mpvbrowserintegration\ff2mpv\ff2mpv.bat",
    "type": "stdio",
    "allowed_extensions": ["ff2mpv@yossarian.net"]
}

and 

@echo off
call python ff2mpv.py

Is there anything further that can be changed in them to make the information of where to find each subsequent file in the list more exacting? Again, without any experience, I almost want to say it might have something to do with how the files aren't quite leading into each other properly for my dumb command prompt to follow, and only seemed to have been doing so at the time I checked the installation because I had previously cd'd to the folder where all of them were already as seen in my opening post.

**Comment by woodruffw** [comment]
I think the problem might be with escaping the backslashes in JSON. Can you try these contents for the `ff2mpv-windows.json`?

```json
{
"name": "ff2mpv",
"description": "ff2mpv's native manifest",
"path": "C:\\Misc\\mpvbrowserintegration\\ff2mpv\\ff2mpv.bat",
"type": "stdio",
"allowed_extensions": ["ff2mpv@yossarian.net"]
}
```

Note the double backslashes -- they're critical.

**Comment by Neidkaris** [comment]
@woodruffw I'm sorry friend, I have done so, but still no response. I have also noticed I've mad a slight mistake when setting the path earlier and pointed it directly to the .bat file rather than just the general folder it was in, but I have also tried variations of the correct escaped backlash path both pointing to the ff2mpv folder and the ff2mpv.bat file directly in the windows-specific AND regular .json files, to still no effect.

**Comment by woodruffw** [comment]
Yeah, I'm at a loss to explain it then. Sorry. @thomastay might have some other ideas, but otherwise I'll just mark this as a bug and leave it open.

**Comment by Neidkaris** [comment]
I understand. It is unfortunate, but regardless of that, thank you for your assistance and patience, friend. :)

**Comment by thomastay** [comment]
@woodruffw It's not in the wiki, since the ff2mpv-windows is slightly different. It points to the local batch file. I found it was not necessary to specify the full path, only the relative path. But things might be different for you, idk. 

A last idea might be to check line endings? It should be CRLF on Windows. 

But yeah sorry @Neidkaris I don't think I can help you as is. I'll try to write up a logger that works sometime this week, and you can try the patch.

**Comment by thomastay** [comment]
@Neidkaris I just realized something. Can you run `mpv <some youtube url>`. Does mpv pop up then?

**Comment by Neidkaris** [comment]
@thomastay Sorry friend, I have just tried that, and it does function if I run mpv directly from the prompt, yes. I've also used the same youtube url I've been testing the extension with all this time, just to make sure.

**Comment by Ashyni** [comment]
Hello, trying to make it work on windows, i find out that when the script ff2mpv.py is called by firefox, the child process is closed as last function `send_message("ok")` is done.
The child process is not closed when we directly start `ff2mpb.bat` or `ff2mpv.py`, something to do with signal, i don't know how python ,windows or firefox handle this. 
You can check this by simply adding a sleep.
```
import time

     Popen(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)
     time.sleep(10)
    # Need to respond something to avoid "Error: An unexpected error occurred"
    # in Browser Console.
    send_message("ok")
```

The workaround i find is to use `run` instead of `Popen`, that way the python script stay open as long as mpv is running.
```
from subprocess import run, DEVNULL

def main():
    message = get_message()
    url = message.get("url")

    mpv_args = ["--no-terminal"]
    args = ["mpv", *mpv_args, "--", url]

    run(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)
```


If someone with more knowledge of python on windows, can tell us how to tell the child process to ignore a kill signal or whatever signal is send, some program doesn't care like `calc` but other like `notepad` or `mpv` don't.

**Comment by Ashyni** [comment]
Actually i finded how, as mention by https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging
```
If you started the native application by sending runtime.sendNativeMessage(), then it is closed after it has received the message and sent a response.

On Windows, the browser puts the native application's process into a Job object, and kills the job.
If the native application launches any additional processes and wants them to remain open after the native application itself is killed,
then the native application must launch the additional process with the CREATE_BREAKAWAY_FROM_JOB flag.
```

and https://docs.microsoft.com/fr-fr/windows/win32/procthread/process-creation-flags?redirectedfrom=MSDN
```
CREATE_BREAKAWAY_FROM_JOB
0x01000000
The child processes of a process associated with a job are not associated with the job. 
If the calling process is not associated with a job, this constant has  no effect. 
If the calling process is associated with a job, the job must  set the JOB_OBJECT_LIMIT_BREAKAWAY_OK limit.
```

So this is enough,
`Popen(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)`
to
`Popen(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL, creationflags=0x01000000)`

**Comment by woodruffw** [comment]
@Ashyni that looks like a likely cause, thanks for digging into it! I'd be happy to accept a PR that uses `creationflags` and `subprocess.CREATE_BREAKAWAY_FROM_JOB` to fix this on Windows.

Ideally it should be flagged off for Windows only, so something like this (in pseudocode):

```python
extra_kwargs = {}
if platform.system() == "Windows":
    extra_kwargs["creationflags"] = subprocess.CREATE_BREAKAWAY_FROM_JOB
Popen(..., **extra_kwargs)
```

**Comment by woodruffw** [comment]
#36 will hopefully fix this, once I cut a new release. I'll reopen if it doesn't.

**Comment by mjhymowitz** [comment]
Hi @woodruffw . I just download ff2mpv today (1/13/2021) installed it and I cant get it to work. If I try to use the extention it pauses the video paying and nothing seems to happened when I use the ention on the thumb nail. I checked the youtube-dl and tried using the check-config-win.py to uninstall and reinstall. I tried editing the ff2mpv-windows.json changing path to path": "C:\\Users\\local\\Documents\\Git\\ff2mpv\\ff2mpv.bat" . 

I tried running the ff2mpv.bat file directly, but I'm assuming something is suppose to be passed into it based off the error it gives after i press control + C.
I also noticed that when I open the registy, I can't find a registry key for ff2mpv.

I'm not sure what else to do and don't want to investigate further without consulting someone. 

Im using windows 10 home
python 3.9.1
git version 2.30.0.windows.1
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  6 10:03:04 +08 2020
FFmpeg library versions:
   libavutil       56.62.100
   libavcodec      58.114.100
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.92.100
   libswresample   3.8.100
FFmpeg version: git-2020-12-05-89e3f5ab

**Comment by woodruffw** [comment]
@mjhymowitz Could you fill all of that information out in a new issue? There should be a custom template for bug reports.

I don't personally use the Windows scripts, so having it in a separate issue will allow me to tag the right people with fresh context and will make it more discoverable to others who might be having the same problem.
