### ISSUE TITLE
MPV window doesn't appear when choosing (no video) option

### ISSUE THREAD

**Issue by meelten** [woodruffw/ff2mpv#32]
When I choose the new "Play in MPV (no video)" option for playing link, the sound just plays in background without showing MPV window so there's no way to easy stop or control playback. For example when I open sound file from hard drive instead there's normal empty/black window which I'd say is expected behavior. 

Could it be fixed to play only audio track but still show window?

**Comment by hexa29** [comment]
You can add `--force-window` option to your mpv config to always show the window.
The no video option was recently removed due to some negative feedback, update your extension to restore the previous behavior.

**Comment by meelten** [comment]
Ah yes, I see. Nevermind then.
