### ISSUE TITLE
Pause youtube video when clicking

### ISSUE THREAD

**Issue by r7l** [woodruffw/ff2mpv#33]
When clicking the button in the upper right corner, it will load the video in the background as expected and show it in a mpv window. But the video inside the browser will keep running and that makes 2 of the same video run at once.

Would it be possible to automatically pause the video inside the Firefox when clicking the ff2mpv button?

**Comment by woodruffw** [comment]
> Would it be possible to automatically pause the video inside the Firefox when clicking the ff2mpv button?

Possibly -- it would be another WebExtension API. I'd be happy to accept a PR for this, if the answer is "yes."

**Comment by woodruffw** [comment]
Did some quick research on this, and it looks like it should be possible to just query the current `document` for `<video>` elements  and do `video.pause()` on them. So it's not a special WebExtension API, but the current extension might need additional permissions to access `document`.

I'm happy to accept a PR for the above.
