### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by tp78903** [woodruffw/ff2mpv#4]
Hi, can the add-on work with Windows? It says "This add-on is not available on your platform."

**Comment by woodruffw** [comment]
In its current state, probably not. Sorry!

I don't own a Windows machine and have no way of developing/testing for Windows. It's something I'd accept a PR for, though.

**Comment by b4zz4** [comment]
@ tp78903 
```
{
    "name": "ff2mpv",
    "description": "ff2mpv's external manifest",
    "path": "C:\python3.exe ff2mpv.py",
    "type": "stdio",
    "allowed_extensions": ["ff2mpv@yossarian.net"]
}
```

**Comment by woodruffw** [comment]
@b4zz4 Would you consider making a PR for that, in the form of a new file (e.g., `ff2mpv.windows.json`?)

**Comment by b4zz4** [comment]
i dont have window :-1: . But aca there are some examples
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#App_side

**Comment by woodruffw** [comment]
I've added @b4zz4's manifest and some information on manifest locations on Windows to the wiki.

**Comment by woodruffw** [comment]
For future reference: #24 added Windows support.

**Comment by Asinin3** [comment]
@woodruffw Is this correct?
![image](https://user-images.githubusercontent.com/15137035/93015478-06533680-f5f9-11ea-9f13-03be67bf13d8.png)
I installed git. Python3, youtube-dl and mpv were already installed and in system path variables.
But the final command gives me this error:
![image](https://user-images.githubusercontent.com/15137035/93015520-59c58480-f5f9-11ea-86a7-31dad122c175.png)

**Comment by woodruffw** [comment]
@Asinin3 It looks like you're trying to run `check-config-win.py` in the wrong directory: you're in mpv's directory, not the ff2mpv clone. You should run it from there.

**Comment by Asinin3** [comment]
Now I get this.
`Unable to create process using '/usr/bin/env/python3 "C:\Users\Someone\ff2mpv\check-config-win.py" '`

**Comment by woodruffw** [comment]
Sorry, I don't know too much else about how that script works (I'm not a Windows user and it was contributed by another ff2mpv user).

@thomastay Any thoughts here? (Sorry for the ping.)

**Comment by thomastay** [comment]
no problem @woodruffw , happy to help.

@Asinin3 %USERPROFILE% is a batch variable, it won't work in a python script. Try making the registry key an absolute path, without the %USERPROFILE% stuff.

**Comment by Asinin3** [comment]
So, it looks like everything is configured properly. The json file, bat file, py file etc are all there. But clicking on the add-on button in Firefox does nothing. Opening the bat file manually does nothing, as does opening the .py file.
![image](https://user-images.githubusercontent.com/15137035/96332591-7186a180-10ac-11eb-9468-b53738fb776e.png)
