### ISSUE TITLE
Content Security Policy: Couldn't Parse invalid host 'wasm-eval', null, Uncaught (in Promise)

### ISSUE THREAD

**Issue by SeagullisLearningToCode** [woodruffw/ff2mpv#41]
When I use the addon a window doesn't pop up and the console returns the statements above, I followed the instructions correctly

**Comment by woodruffw** [comment]
Hmm. That's weird. `ff2mpv` doesn't use any WebAssembly, so my best guess is that you tried to play a URL (somehow) violated a site's CSP rules.

Do you have an example link that I could try to repro with?

**Comment by SeagullisLearningToCode** [comment]
> Hmm. That's weird. `ff2mpv` doesn't use any WebAssembly, so my best guess is that you tried to play a URL (somehow) violated a site's CSP rules.
> 
> Do you have an example link that I could try to repro with?

It's Youtube

**Comment by woodruffw** [comment]
> https://www.youtube.com/watch?v=Gl_H-e4UUiA

Thanks. I'm unable to repro with that link, but since it's a CSP error it's possible that GitHub's CSP policy isn't interfering with it here.

Do you have a link to the original page that that link was on, or a similar page that causes the same issue?

**Comment by SeagullisLearningToCode** [comment]
> > https://www.youtube.com/watch?v=Gl_H-e4UUiA
> 
> Thanks. I'm unable to repro with that link, but since it's a CSP error it's possible that GitHub's CSP policy isn't interfering with it here.
> 
> Do you have a link to the original page that that link was on, or a similar page that causes the same issue?

about:devtools-toolbox?type=extension&id=ff2mpv%40yossarian.net

**Comment by woodruffw** [comment]
> about:devtools-toolbox?type=extension&id=ff2mpv%40yossarian.net

I'm not sure what to do with this -- there doesn't seem to be anywhere on this page for loading a separate URL with `ff2mpv`.

**Comment by SeagullisLearningToCode** [comment]
no the issue is that it doesn't open MPV or clicking the button doesn't do anything when on a valid page

**Comment by woodruffw** [comment]
Okay. I need some more information:

* Your host OS 
* Your Firefox version
* Whether you're doing anything weird in your `about:config` that could mess with extension permissions

**Comment by SeagullisLearningToCode** [comment]
MacOSX (Pre-BigSur) 10.15.7
84.0.1
seeing what is the issue with it not opening MPV

**Comment by woodruffw** [comment]
Okay. I'm still unable to reproduce this on Linux. I'll try on a Mac when I have some free time.

In the mean time, please go through your `about:config` and make sure you don't have anything enabled that would interfere with Firefox's ability to inject extensions into your pages. That's the only thing I can think of, assuming that you followed the instructions correctly.

**Comment by woodruffw** [comment]
I'm also unable to repro this on macOS. Marking as "candidate" since nobody else has reported this particular issue and I don't have any further ideas.
