### ISSUE TITLE
Clicking to Play with MPV does not work. 

### ISSUE THREAD

**Issue by Werner1201** [woodruffw/ff2mpv#42]
I've installed ff2mpv and the native client but nothing seem to change that I can't make ff2mpv open any youtube video, but I can open them with mpv and the video link in the terminal. 
I'm using Kubuntu 20.04 and I have mpv installed tthrough apt and youtube-dl through pip3. 
I'm thinking it has some problem with the url it's receiving from Firefox. but I can't confirm since I don't know how to send a message to the addon. I'll try to change the python script to run with a fixed url to see if it works

**Comment by Werner1201** [comment]
I've debugged the extension on the browser and I seems to not give any errors when calling this command ```browser.runtime.sendNativeMessage("ff2mpv", { url: url }); ```
![bugreport](https://user-images.githubusercontent.com/8631657/103114596-0cb46e00-463e-11eb-919b-f48b3f770b3f.png)

**Comment by Werner1201** [comment]
I'll try to open a terminal with the python script to see if the sendNativeMessage is working

**Comment by Werner1201** [comment]
it seems like the python get message does not work.

**Comment by Werner1201** [comment]
I've discorvered it executes the python script but it get's stuck at the yt_dl hook 
![anotherbugreport](https://user-images.githubusercontent.com/8631657/103117328-a254fb00-4648-11eb-9e41-a5073c24d363.png)
I don't know if it's a problem with my system or not.

**Comment by Werner1201** [comment]
SInce I can run it with mpv [youtube-link] in the ternimal I don't see why it does not work on the script

**Comment by Werner1201** [comment]
![aabugreport](https://user-images.githubusercontent.com/8631657/103117994-c403b180-464b-11eb-81e6-fd09358d5d8d.png)
I changed a little to see any glances at why it is not working and the terminal says the yt-dl-hook does not exist but it exists

**Comment by Werner1201** [comment]
Same video but not working with the python script but working with the terminal
![samevideo](https://user-images.githubusercontent.com/8631657/103118170-6d4aa780-464c-11eb-9310-19dbde209def.png)

**Comment by Werner1201** [comment]
![image](https://user-images.githubusercontent.com/8631657/103118714-e814c200-464e-11eb-8d2a-262f5cb36ec5.png)
I found out that there's a permission problem with the way firefox is executing the python command and as consequence it causes yt_dl_hook to have permission problems. as demonstraded with the sudo command on the image

**Comment by Werner1201** [comment]
The Addon works with this video here [video](https://r2---sn-uxaxh5g-bpbz.googlevideo.com/videoplayback?expire=1608932915&ei=s-3lX8mgBdfcj-8PhuKBqAU&ip=2607:5300:60:7317::&id=2cdedeced786dfe0&itag=18&source=blogger&susc=bl&mime=video/mp4&vprv=1&dur=1434.017&lmt=1507650829011651&sparams=expire,ei,ip,id,itag,source,susc,mime,vprv,dur,lmt&sig=AOq0QJ8wRQIhALIL8rPcrEpVOSJR2E8NQ_tKeqI92PsOuH1cHoZJazVCAiB2ofgTw0MjTvJ9Omm21Wc586XDDZmHGUItVGJxfX1KBw%3D%3D&redirect_counter=1&rm=sn-p5qyk7l&req_id=4efa899e837a36e2&cms_redirect=yes&ipbypass=yes&mh=AO&mip=191.47.77.184&mm=31&mn=sn-uxaxh5g-bpbz&ms=au&mt=1608907006&mv=m&mvi=2&pl=21&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIhAN-rrdgEdewgo6gp2gCr4KZhXfB-M8IQLBw-_vUKYcHmAiBSWZYd3aLUCOr6qQQQBQwgBgLWThg8R_mDUFbWVW9xsw%3D%3D)
just click play with mpv above the video

**Comment by Werner1201** [comment]
Bitchute doesn't work as well as liveleak. This sites I tested using the original python script

**Comment by woodruffw** [comment]
> I found out that there's a permission problem with the way firefox is executing the python command and as consequence it causes yt_dl_hook to have permission problems. as demonstraded with the sudo command on the image

I'm not 100% sure what's happening here, but this sounds like a system configuration issue. 

`ff2mpv` itself does **exactly** one thing: it sends a message to the native client, which in turn is responsible for unpacking the message and executing `mpv`. `mpv`, in turn, needs to appropriately execute `youtube-dl`, which is where the breakdown seems to be happening on your system. Firefox doesn't know or have any say over how `youtube-dl` is executed.

If I had to guess, the issue might be that you're installing `youtube-dl` into a system directory, hence the root permissions. Try removing it and using `pip3 install --user youtube-dl` instead.

**Comment by Werner1201** [comment]
But I don't need root permissions to run the command, I demonstrated that
the error that is causing when I run play with mpv is the same as if I'd
ran the mpv command with sudo.

Em sáb, 26 de dez de 2020 00:27, William Woodruff <notifications@github.com>
escreveu:

**Comment by Werner1201** [comment]
I have YouTube-dl via pip3 since it's the only way I can have the latest
one with ease of access. the only other way I can install it is compiling
from source, which I didn't do.

Em sáb, 26 de dez de 2020 00:27, William Woodruff <notifications@github.com>
escreveu:

**Comment by Werner1201** [comment]
To phrase it better. I'm saying the opposite that you are claiming. My system does not need sudo to run the commands, the ```mpv [video_link``` works fine in the terminal, the only thing that doesn't it's the execution of the comm inside the Python script. What I showed here is that it seems like the python script that is being ran by Firefox from ff2mpv is running the mpv command with privileges as I showed the yt-dl_hook error of permissions, and I showed that the only way in my system to get this yt-dl_hook error when running that command is by running with sudo, which indicates a permission problem with the Firefox running the command. That being said, I'll try the pip command to see if this fixes.

**Comment by Werner1201** [comment]
this is where the pip3 youtube-dl was 
![image](https://user-images.githubusercontent.com/8631657/103151026-f8b15f00-4758-11eb-8ada-d86e8edd7dc8.png)

**Comment by Werner1201** [comment]
this is where it is installed 
![image](https://user-images.githubusercontent.com/8631657/103151047-2a2a2a80-4759-11eb-9048-14a82a22dbc8.png)

**Comment by Werner1201** [comment]
here is the mpv info just in case 
![image](https://user-images.githubusercontent.com/8631657/103151074-7ffed280-4759-11eb-9d1c-1c25c1071291.png)

**Comment by Werner1201** [comment]
i'm going to to do a cold boot and see if this works

**Comment by Werner1201** [comment]
No change. 

https://user-images.githubusercontent.com/8631657/103151167-79248f80-475a-11eb-90e7-3c5b181efce0.mp4

**Comment by woodruffw** [comment]
> What I showed here is that it seems like the python script that is being ran by Firefox from ff2mpv is running the mpv command with privileges as I showed the yt-dl_hook error of permissions, and I showed that the only way in my system to get this yt-dl_hook error when running that command is by running with sudo, which indicates a permission problem with the Firefox running the command.

Okay, now I understand. Thanks.

Could you give me the outputs to each of these commands?

```bash
which firefox mpv youtube-dl
stat firefox mpv youtube-dl
```

**Comment by woodruffw** [comment]
My current guess is that Firefox is running as another user, which means that the native client doesn't have `youtube-dl` in its `PATH`. That, or it's being run through a mechanism that doesn't start it through a login shell, which is where people usually put their `PATH` modifications.

So, another question: how are you running Firefox?

**Comment by Werner1201** [comment]
> > What I showed here is that it seems like the python script that is being ran by Firefox from ff2mpv is running the mpv command with privileges as I showed the yt-dl_hook error of permissions, and I showed that the only way in my system to get this yt-dl_hook error when running that command is by running with sudo, which indicates a permission problem with the Firefox running the command.
> 
> Okay, now I understand. Thanks.
> 
> Could you give me the outputs to each of these commands?
> 
> ```shell
> which firefox mpv youtube-dl
> stat firefox mpv youtube-dl
> ```

Strangely enough stat doesn't give me anything with the program names
![image](https://user-images.githubusercontent.com/8631657/103156106-24960a00-4784-11eb-85b5-1c2cd21e638e.png)

**Comment by Werner1201** [comment]
here is stats with the place of the programs 
![image](https://user-images.githubusercontent.com/8631657/103156135-68890f00-4784-11eb-91a6-ff13dbf969d0.png)

**Comment by Werner1201** [comment]
looks like firefox runs using root

**Comment by Werner1201** [comment]
only the youtube-dl is uid user

**Comment by woodruffw** [comment]
> Strangely enough stat doesn't give me anything with the program names

Whoops, that was my fault. Looks like you figured it out, though.

> only the youtube-dl is uid user

Those are just the file UID/GID, which don't necessarily reflect the process's runtime (E)UID and (E)GID. It makes sense that those two are owned by `root`, since they're presumably installed by the system package manager.

Can you give me the result of this command, while running Firefox in the background?

```bash
ps aux | grep firefox
```

Also, just FYI: I get a separate notification every time you write a separate comment on this issue. If you can, please try to consolidate your comments so that this thread is less noisy/easier for others to cross-reference in the future.

**Comment by Werner1201** [comment]
> > Strangely enough stat doesn't give me anything with the program names
> 
> Whoops, that was my fault. Looks like you figured it out, though.
> 
> > only the youtube-dl is uid user
> 
> Those are just the file UID/GID, which don't necessarily reflect the process's runtime (E)UID and (E)GID. It makes sense that those two are owned by `root`, since they're presumably installed by the system package manager.
> 
> Can you give me the result of this command, while running Firefox in the background?
> 
> ```shell
> ps aux | grep firefox
> ```
> 
> Also, just FYI: I get a separate notification every time you write a separate comment on this issue. If you can, please try to consolidate your comments so that this thread is less noisy/easier for others to cross-reference in the future.

Okay, I'll try that command, And I'll consolidate the replies. 
here's the result of the ps | grep command: (figured a text file would be more readable and grepable for you
[ps.txt](https://github.com/woodruffw/ff2mpv/files/5743443/ps.txt)

**Comment by woodruffw** [comment]
Okay, Firefox is definitely running as your user. So that's not the problem.

How exactly are you running Firefox? For example: are you clicking on an icon to start it, or are you running it through some sort of DE/WM launcher?

**Comment by Werner1201** [comment]
I'm running it with a icon from the Latte Dock, but the icon comes from the
app menu that gets the programs from a folder with the .desktop icons the
Firefox is run with the command ```firefox %U```

Em sáb, 26 de dez de 2020 14:52, William Woodruff <notifications@github.com>
escreveu:

**Comment by woodruffw** [comment]
Okay. Two things, then:

* Try running Firefox from a terminal (just run `firefox`), and then try using `ff2mpv`.
* If the above works, try modifying your `.desktop` file to something like this:

```
Exec=bash -c "firefox %U"
```

...and let me know if that works.

**Comment by Werner1201** [comment]
May I add that my shell is zsh. Will it influence the result?

Em sáb, 26 de dez de 2020 16:19, William Woodruff <notifications@github.com>
escreveu:

**Comment by Werner1201** [comment]
I just tested running firefox with bash -c in the ternimal and the extension worked but when I write it to the execution .desktop it does not work

**Comment by Werner1201** [comment]
So, I'm making a new reply because it seems to be a problem with the way the desktop links are put together that the %U parameter after the program makes the program not work if run with bash -c
![image](https://user-images.githubusercontent.com/8631657/103158200-25399b00-479a-11eb-910f-1c468f2aa613.png)
When it is without the default %U the addon works. I think this "bug" is related to zsh and the way it is handeling the execution of the programs on Kubuntu

**Comment by woodruffw** [comment]
> May I add that my shell is zsh. Will it influence the result?

It shouldn't, but I don't know anything about zsh. 

> Yep. Confirmed, I can make it work if I remove the %U command from the .desktop even without the bash -c there, this means it has some problem with this %U

Just to clarify: you mean that `ff2mpv` works without any other changes, as long as you remove `%U` from your `.desktop` file?

**Comment by Werner1201** [comment]
> > May I add that my shell is zsh. Will it influence the result?
> 
> It shouldn't, but I don't know anything about zsh.
> 
> > Yep. Confirmed, I can make it work if I remove the %U command from the .desktop even without the bash -c there, this means it has some problem with this %U
> 
> Just to clarify: you mean that `ff2mpv` works without any other changes, as long as you remove `%U` from your `.desktop` file?

Yes that's what I meant

**Comment by woodruffw** [comment]
> Yes that's what I meant

Okay, that's a mystery to me.  My understanding of `%U` is that it's used for drag-and-drop operations with one or more URLs, so it shouldn't affect addons whatsoever.

In any case, it's Linux distro dumbness and therefore outside of the scope of `ff2mpv`. I'll add some notes to the Wiki documenting it as a potential problem.

**Comment by Werner1201** [comment]
> . My understanding of `%U` is that it's used for drag-and-drop operations with one or more URLs, so it shouldn't affect addons whatsoever.

Maybe It affects it because you communicate with outside programs ? with the message thing ? 

> In any case, it's Linux distro dumbness and therefore outside of the scope of `ff2mpv`. I'll add some notes to the Wiki documenting it as a potential problem.

Okay, Thanks for your patience. It kinda works and the %U doesn't really affect me very much.

**Comment by woodruffw** [comment]
> Maybe It affects it because you communicate with outside programs ? with the message thing ?

Possibly, but that isn't documented anywhere. That would also break a whole bunch of other extensions (like password managers) that use the same mechanism, which is why it surprises me.



> Okay, Thanks for your patience. It kinda works and the %U doesn't really affect me very much.

No problem. I've added some notes to the wiki reflecting your problem. Thanks for helping debug it.
