### ISSUE TITLE
Videos don't open at all

### ISSUE THREAD

**Issue by Raudonkepuris** [woodruffw/ff2mpv#43]
I had two problems with installation:
1. install.sh script tried installing to "/home/william/scripts/ff2mpv", I had to install it manually and it still didn't work.
2. I had to delete the argument "--no-terminal" (from the python script) to get it to work.

It might be related to the fact that I have zsh alias "mpv="devour mpv"".

My setup is:
Artix runit, dwm, st, mpv 1:0.33.0-3, youtube-dl 2020.12.22-1.

**Comment by Werner1201** [comment]
I'm on Kubuntu and I already tried a lot of things but when firefox executes the python script it seems like the script is running with privileges. becuse yt-dl_hook does not have permissions and it only has this problem when running mpv with sudo.

**Comment by woodruffw** [comment]
The first sounds like a bug in the install script, which @Atemu  recently modified. Any thoughts? I don't use it personally, so I won't be of much help with it.

I'm not sure about the second. How old is your copy of MPV? What does it say when you try to pass `--no-terminal` manually?

**Comment by woodruffw** [comment]
> I'm on Kubuntu and I already tried a lot of things but when firefox executes the python script it seems like the script is running with privileges. becuse yt-dl_hook does not have permissions and it only has this problem when running mpv with sudo.

@Werner1201 This is not a supported configuration. You shouldn't be running Firefox, or MPV, or youtube-dl as a root user or with any sort of effective root permissions. I followed up on your separate issue; let me know if that helps.

**Comment by Atemu** [comment]
I just ran the install script again and it worked as expected. Could you `bash -x` it and give us the resulting JSON Raudonkepuris?

Does mpv work without the alias? It only exists in interactive zsh sessions and nowhere else.

**Comment by Werner1201** [comment]
> I just ran the install script again and it worked as expected. Could you `bash -x` it and give us the resulting JSON Raudonkepuris?
> 
> Does mpv work without the alias? It only exists in interactive zsh sessions and nowhere else.

![image](https://user-images.githubusercontent.com/8631657/103151237-ffd96c80-475a-11eb-8b80-aa5ebb5296e5.png)

**Comment by Raudonkepuris** [comment]
> I'm not sure about the second. What does it say when you try to pass `--no-terminal` manually?

It played in all scenarios I tried (I had disabled the alias while testing)
![Pic-crop-201226-1521-14](https://user-images.githubusercontent.com/54080687/103152205-51e7b580-478e-11eb-8170-1a4cb82666df.png)




> I just ran the install script again and it worked as expected. Could you `bash -x` it and give us the resulting JSON Raudonkepuris?
> 
> Does mpv work without the alias? It only exists in interactive zsh sessions and nowhere else.

Mpv does work both with and without the alias, the picture above confirms that.

![Pic-crop-201226-1526-01](https://user-images.githubusercontent.com/54080687/103152245-d6d2cf00-478e-11eb-89ae-b141f4c71043.png)

It might've been a whole other problem that it wouldn't play videos, but I can't think of anything else I did while fixing it.

**Comment by woodruffw** [comment]
> It might've been a whole other problem that it wouldn't play videos, but I can't think of anything else I did while fixing it. Maybe it was zsh's problem.

I'm not sure, but the script definitely wasn't written with zsh in mind originally. It wouldn't surprise me if it did the wrong thing.

I'm happy to accept a PR that rewrites it in POSIX `sh` or, even better, uses a Makefile to drive installation.

**Comment by woodruffw** [comment]
(Closing since it sounds like it's working now.)
