### ISSUE TITLE
Add Compatibility for Pluto.tv streaming

### ISSUE THREAD

**Issue by scorpius2k1** [woodruffw/ff2mpv#45]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Compatibility with Pluto TV => https://pluto.tv

**Describe alternatives you've considered**
Firefox PiP, but prefer MPV usage.

**Additional context**
None.

**Comment by woodruffw** [comment]
`ff2mpv` is a Firefox extension that wraps MPV, which in turn wraps `youtube-dl` for actual stream extraction.

You'll need to file this report with them: https://github.com/ytdl-org/youtube-dl/issues/new/choose
