### ISSUE TITLE
fullscreen videos are stretched on my 21:9 display

### ISSUE THREAD

**Issue by Pistrie** [woodruffw/ff2mpv#47]
## Describe the bug

Videos will be stretched if they are not your native aspect ratio. 4:3 and 16:9 videos will be stretched to 21:9 on my display when playing fullscreen, and 32:9 videos will play condensed

## Reproduction steps

1. Open a video with a different than native aspect ratio with ff2mpv
2. Your video will play stretched or condensed

## Expected behavior

The video will play with the correct aspect ratio with black bars on the sides (or bottom and top, if the aspect ratio is higher than your own)
[32:9 video for reference](https://youtu.be/CtTuBDIPcww)

## Screenshots (optional)

![2021-03-01_13-22](https://user-images.githubusercontent.com/39904003/109496621-313f2300-7a91-11eb-8f6e-dfda37b98e17.png)
![2021-03-01_13-23](https://user-images.githubusercontent.com/39904003/109496715-53d13c00-7a91-11eb-8196-def7e8aa7723.png)
![2021-03-01_13-32](https://user-images.githubusercontent.com/39904003/109497602-95161b80-7a92-11eb-902e-6cb60b34711f.png)

## Platform information

 - OS information: 64 bit GNU/Linux
 - Firefox version: 85.0
 - MPV version: mpv 0.33.0-dirty
 - youtube-dl version: 2021.02.22

**Comment by woodruffw** [comment]
Thanks for the report. I don't have a 21:9 monitor to test with, but I'll give your samples a spin tonight.

**Comment by woodruffw** [comment]
...I said, and then forgot. Sorry. Will try tonight.

**Comment by woodruffw** [comment]
I gave that video a try, and my version of `mpv` (0.32.0) inserted vertical bars that way I expected. That being said, I'm testing on a 16:9 monitor.

Do you have anything unusual in your MPV config? At the end of the day, all `ff2mpv` does is call `mpv`; it doesn't do anything special in terms of configuration or changing any of your normal defaults.

**Comment by Pistrie** [comment]
Yeah I'm assuming it's something on my end. I'll try a reinstall and see how it goes

**Comment by woodruffw** [comment]
Cool. You might also want to try playing those videos manually through `mpv`, passing in `--keepaspect`. If that works, then it's likely a misconfiguration somewhere.
