### ISSUE TITLE
Problems getting ff2mpv up and running on macOS

### ISSUE THREAD

**Issue by filcode** [woodruffw/ff2mpv#48]
## Describe the bug

I am trying to use ff2mpv extension on the most recent version of Firefox for macOS, but with no success. When I try to run videos with ff2mpv the mpv.app tries to open, but close immediately.

I followed the instructions in the following link:

[1] https://github.com/woodruffw/ff2mpv/wiki/Installation-on-macOS

I tried ff2mpv and ff2mpv.py both with no success. I prefer to use ff2mpv (the Ruby script). I opened it with nano editor to make the changes that is recommend in [1] because my mpv.app is on the /Applications folder. However, I have until now no success.

Even with python 3.9 installed, using ff2mpv.py, with changes recommended in [1], I had until now no success. However, like I said previously I prefer to use ff2mpv (the Ruby script) instead.

I tried also script ./install, but also with the same result. No sucess.

My mpv app version is 0.33 and youtude-dl version is 2021.03.14.

## Reproduction steps

[1] https://github.com/woodruffw/ff2mpv/wiki/Installation-on-macOS

## Platform information

 - OS information: macOS Catalina 10.15.7
 - Firefox version: 86.0.1 (64-bit)
 - MPV version: 0.33
 - youtube-dl version: 2021.03.14.

**Comment by woodruffw** [comment]
Thanks for the report. Could you share the following information?

1. A `diff` of your changes to `ff2mpv` (the Ruby script), **or** the entire script
2. Any errors or warnings that appear in the Firefox JavaScript console when you attempt to play a video

**Comment by filcode** [comment]
H

> Thanks for the report. Could you share the following information?
> 
> 1. A `diff` of your changes to `ff2mpv` (the Ruby script), **or** the entire script
> 2. Any errors or warnings that appear in the Firefox JavaScript console when you attempt to play a video

Hi,

Please consider in attachment the "Info.zip" file with the log from the console (only three warnings) and the entire script.

Regards,

[Info.zip](https://github.com/woodruffw/ff2mpv/files/6185744/Info.zip)

**Comment by woodruffw** [comment]
Thanks. The warnings in your log look unrelated and the changes you made to `ff2mpv` look fine, at a quick glance.

Next step: could you try running `mpv` directly from a terminal, passing it a YouTube URL?

```bash
cd /Applications/mpv.app/Contents/MacOS
./mpv "https://www.youtube.com/watch?v=KmtzQCSh6xk"
```

If that doesn't work, please record and upload any errors it spits out. If it does work, it's probably something about your Firefox environment.

**Comment by filcode** [comment]
> Thanks. The warnings in your log look unrelated and the changes you made to `ff2mpv` look fine, at a quick glance.
> 
> Next step: could you try running `mpv` directly from a terminal, passing it a YouTube URL?
> 
> ```shell
> cd /Applications/mpv.app/Contents/MacOS
> ./mpv "https://www.youtube.com/watch?v=KmtzQCSh6xk"
> ```
> 
> If that doesn't work, please record and upload any errors it spits out. If it does work, it's probably something about your Firefox environment.

It worked, but there were some errors on terminal because I put ff2mpv Ruby script on .conf/mpv/scripts. Please consider the record.


https://user-images.githubusercontent.com/81129688/112070896-9f45aa00-8b66-11eb-92a9-4a9f41d7d015.mov

**Comment by filcode** [comment]
> > Thanks. The warnings in your log look unrelated and the changes you made to `ff2mpv` look fine, at a quick glance.
> > Next step: could you try running `mpv` directly from a terminal, passing it a YouTube URL?
> > ```shell
> > cd /Applications/mpv.app/Contents/MacOS
> > ./mpv "https://www.youtube.com/watch?v=KmtzQCSh6xk"
> > ```
> > 
> > 
> > If that doesn't work, please record and upload any errors it spits out. If it does work, it's probably something about your Firefox environment.
> 
> It worked, but there were some errors on terminal because I put ff2mpv Ruby script on .conf/mpv/scripts. Please consider the record.
> 
>  Screen.Recording.2021-03-22.at.23.27.56.mov

Hi again, I use the following extensions on Firefox:
- ublock origin
- Https Everywhere
- Privacy Badger
- ClearURLs
-

**Comment by woodruffw** [comment]
Okay. `ff2mpv` should **not** be loaded as one of MPV's scripts: it's a wrapper than invokes `mpv`, not something that MPV itself communicates with. Could you try removing it from MPV's scripts and seeing if that fixes things?

**Comment by filcode** [comment]
> Okay. `ff2mpv` should **not** be loaded as one of MPV's scripts: it's a wrapper than invokes `mpv`, not something that MPV itself communicates with. Could you try removing it from MPV's scripts and seeing if that fixes things?

I put the file ff2mpv (Ruby script) in a folder called "a" on the Desktop and I no longer get the error in the terminal. However, changing the path in the "ff2mpv.json" file to ff2mpv (Ruby script) located in "a" folder on the Desktop, ff2mpv (Ruby script) still does not work in Firefox. Please consider the attached recording. 

https://user-images.githubusercontent.com/81129688/112075307-2ba89a80-8b70-11eb-9286-5042bce6c6ea.mov

**Comment by woodruffw** [comment]
By "still does not work," I'm assuming you mean the same behavior where it starts MPV but then quits?

**Comment by filcode** [comment]
> By "still does not work," I'm assuming you mean the same behavior where it starts MPV but then quits?

Yes, the mpv.app icon on the dock jumps, but it does nothing.

**Comment by woodruffw** [comment]
Okay, that means that it's getting to MPV but something about MPV or its config is causing it to quit. What happens when you comment out your personal config entirely?

**Comment by filcode** [comment]
> Okay, that means that it's getting to MPV but something about MPV or its config is causing it to quit. What happens when you comment out your personal config entirely?

I removed the file "mpv.conf" from the folder "./config/mpv/" and the same thing happens, that is, the mpv.app icon on the dock jumps, but it does nothing.

**Comment by woodruffw** [comment]
Okay. Thanks for bearing with me. I have a Mac at my disposal, so I'll try to reproduce your exact setup tomorrow.

**Comment by filcode** [comment]
> Okay. Thanks for bearing with me. I have a Mac at my disposal, so I'll try to reproduce your exact setup tomorrow.

Please consider my mpv.conf file attached.
[mpv.conf.zip](https://github.com/woodruffw/ff2mpv/files/6186318/mpv.conf.zip)

**Comment by filcode** [comment]
I found the reason for the error "unparseable extra characters".

Instead of:
alang:eng,en,por,pt
slang:eng,en,por,pt

Should be:
alang=eng,por,en,pt
slang:=eng,por,en,pt

**Comment by woodruffw** [comment]
I'm trying to test now. Where did you get your `mpv.app` from? The recommended installation for macOS is `brew install mpv`, which installs a direct binary instead of an application bundle.

**Comment by woodruffw** [comment]
I wasn't able to find a `mpv.app` to test with, but I did `brew install mpv` and was able to confirm that `ff2mpv` doesn't work "out of the box" on my macOS installation.

I did some debugging, and this looks like a return of the `PATH` issue that some people have seen before: the default graphical login environment on macOS doesn't have `/usr/local/bin` in its `PATH`, so the following happens:

1. Firefox calls `ff2mpv` (the Ruby script) with its current `PATH`, which doesn't include `/usr/local/bin`
2. `ff2mpv` either invokes `mpv.app` directly (your case) or tries to find `mpv` on the `PATH` (my case)
3. If it can't find `mpv` on the `PATH`, it fails silently (my case)
4. If it **can** find `mpv`, then it calls `mpv`
5. `mpv` tries to find `youtube-dl` on the `PATH`, which again may fail silently if `/usr/local/bin` isn't present

I added a quick-and-dirty hack to my local copy that injects `/usr/local/bin` into my `PATH` and, sure enough, `ff2mpv` began working.

The correct fix to this is to modify `launchd`'s configuration to include `/usr/local/bin` in the environment of every spawned process. However, this is invasive and most users will struggle to make the correct changes. For the time being, I'll open up a PR with my "fix" and you can let me know if it works for you. If it does, I'll merge it.

**Comment by filcode** [comment]
> I'm trying to test now. Where did you get your `mpv.app` from? The recommended installation for macOS is `brew install mpv`, which installs a direct binary instead of an application bundle.

I get the mpv.app from here:
https://laboratory.stolendata.net/~djinn/mpv_osx/

**Comment by filcode** [comment]
> I wasn't able to find a `mpv.app` to test with, but I did `brew install mpv` and was able to confirm that `ff2mpv` doesn't work "out of the box" on my macOS installation.
> 
> I did some debugging, and this looks like a return of the `PATH` issue that some people have seen before: the default graphical login environment on macOS doesn't have `/usr/local/bin` in its `PATH`, so the following happens:
> 
> 1. Firefox calls `ff2mpv` (the Ruby script) with its current `PATH`, which doesn't include `/usr/local/bin`
> 2. `ff2mpv` either invokes `mpv.app` directly (your case) or tries to find `mpv` on the `PATH` (my case)
> 3. If it can't find `mpv` on the `PATH`, it fails silently (my case)
> 4. If it **can** find `mpv`, then it calls `mpv`
> 5. `mpv` tries to find `youtube-dl` on the `PATH`, which again may fail silently if `/usr/local/bin` isn't present
> 
> I added a quick-and-dirty hack to my local copy that injects `/usr/local/bin` into my `PATH` and, sure enough, `ff2mpv` began working.
> 
> The correct fix to this is to modify `launchd`'s configuration to include `/usr/local/bin` in the environment of every spawned process. However, this is invasive and most users will struggle to make the correct changes. For the time being, I'll open up a PR with my "fix" and you can let me know if it works for you. If it does, I'll merge it.

To had a Directory to the PATH you can use:

Create ~/.zshenv:
`nano ~/.zshenv`

Add a directory to the path, in this case, /usr/local/bin:
`export PATH="/usr/local/bin:$PATH"`

What do you think about this solution?

**Comment by woodruffw** [comment]
The steps you list above are for adding a directory to the `PATH` for interactive terminal shells. macOS uses a completely different subsystem for graphical login environments, one that doesn't load *any* shell profiles or rc-files before hand. That's why `mpv` works when spawned in a terminal but doesn't work when spawned by Firefox.

Please try the patch in #49.

**Comment by woodruffw** [comment]
(Another solution would be to spawn `mpv` in `ff2mpv` via `bash -lc` or `zsh -lc`, but I really dislike that solution: it introduces a bunch of potential side effects from loading the user's entire login profile, and is a trivial code injection vector.)

**Comment by filcode** [comment]
> (Another solution would be to spawn `mpv` in `ff2mpv` via `bash -lc` or `zsh -lc`, but I really dislike that solution: it introduces a bunch of potential side effects from loading the user's entire login profile, and is a trivial code injection vector.)

I agree.

**Comment by filcode** [comment]
> The steps you list above are for adding a directory to the `PATH` for interactive terminal sessions. macOS uses a completely different subsystem for graphical login environments, one that doesn't load _any_ shell profiles or rc-files before hand. That's why `mpv` works when spawned in a terminal but doesn't work when spawned by Firefox.
> 
> Please try the patch in #49.

Do you expect to have a new version of ff2mpv soon with this issue resolved?

**Comment by woodruffw** [comment]
If you can confirm that it works, I'll merge #49 into `master` and cut a bugpoint release to indicate that the client has been fixed.

**Comment by filcode** [comment]
> If you can confirm that it works, I'll merge #49 into `master` and cut a bugpoint release to indicate that the client has been fixed.

I can confirm that it works.

**Comment by woodruffw** [comment]
Great, good to hear. I'll merge it tonight.

**Comment by woodruffw** [comment]
Okay, this has been cut as 3.7.1. Thanks again for the report and for helping me debug.

**Comment by filcode** [comment]
> Okay, this has been cut as 3.7.1. Thanks again for the report and for helping me debug.

You welcome.
