### ISSUE TITLE
Installation tutorial (native-messaging-hosts not found)

### ISSUE THREAD

**Issue by prog-amateur** [woodruffw/ff2mpv#5]
Hello, first of all, thank you for your web extension. 
I have an issue with the installation : I have downloaded the zip file from github. 
I have put ff2mpv.py in a location. So far, so good. 
Now, when I try to find the path ~/.mozilla/native-messaging-hosts/ I can't find it. 
Maybe it is a new organization from Firefox, or because I use Linux (Xubuntu). 

Please, do you know how to find it under Linux ? I have googled but nothing found. Thank you for your kind help.

**Comment by woodruffw** [comment]
`~/.mozilla/native-messaging-hosts/` is a subdirectory under your home directory ("`~`"). You need to create it if it doesn't exist already (Firefox doesn't create it by default).

You can run this to create it:

```
$ mkdir -p ~/.mozilla/native-messaging-hosts/
```

Once that's done, copy the `ff2mpv.json` in the ZIP you downloaded into that directory (make sure to update it to reference the location of `ff2mpv.py`!):

```
$ cp ff2mpv.json ~/.mozilla/native-messaging-hosts/
```

Once that file is in place and the extension is installed, everything should work as expected. Let me know if you run into any problems!

**Comment by prog-amateur** [comment]
Hi, thank you so much for your quick answer ! I will try and feedback today hopefully.

**Comment by prog-amateur** [comment]
It still doesn't work, I am sure I have mistaken somewhere. Let's go back to the very beginning : 

1. Installation of MPV from Software store 
2. Installation of your Web extension 
3. Download the ZIP file from Github
4. Put `ff2mpv.py` into `/home/prog-amateur/movies/ff2mpv` (for your information `ff2mpv` is a folder) 
5. Open a terminal and run : 
```
$ chmod +x ff2mpv.py
$ mkdir -p ~/.mozilla/native-messaging-hosts/
$ cd /home/prog-amateur/movies/ff2mpv
$ cp ff2mpv.json ~/.mozilla/native-messaging-hosts/
```
6. Open `ff2mpv.json` and change only `"path"` section from `"/home/william/scripts/ff2mpv"` to `"/home/prog-amateur/movies/ff2mpv"`

Then when I go on a youtube video, it doesn't work. 
Shall I also change the `"name"` section from `"ff2mpv"` to `"ff2mpv.py"` in `ff2mpv.json` file ? 
Did I executed the python file well ? 

Thank you very much.

**Comment by prog-amateur** [comment]
Ok I have found the issue : 
I had to make the path to `"/home/prog-amateur/movies/ff2mpv/ff2mpv.py"`. 
The hardware acceleration is not enabled but at least the web extension works.

**Comment by woodruffw** [comment]
Yep, the path needs to be the full path to the script. Glad you got it working!

As for hardware acceleration: it's probably an MPV configuration thing. Their manual (https://mpv.io/manual/stable/) probably has some guides for setting that up.

**Comment by alekksander** [comment]
i also had to put „/ff2mpv.py” at the end of line. made it work perfectly (although i use Your competitor, because i prefer smplayer over mpv in most cases)
