### ISSUE TITLE
(MacOSX) mpv+X11 backend = no luck?

### ISSUE THREAD

**Issue by mrkapqa** [woodruffw/ff2mpv#51]
Hello ,

installed your new ff2mpv via ./install.sh
but the video would not play.

mpv is installed via macports with x11 backend;
the ff2mpv would call the x11 (xquartz) window, but mpv would not play.

could you give me some hint on where to start debug?

thanks.

**Comment by mrkapqa** [comment]
i am using an older mac os 10.8 with firefox legacy 71.0 (64bit)

![Screen Shot 2021-04-19 at 12 52 51 PM](https://user-images.githubusercontent.com/12947465/115225419-57d31f00-a10e-11eb-9981-3b7c00a5e609.png)

**Comment by woodruffw** [comment]
Could you please go back and fill out each of the fields in the "bug report" issue template? The details in those fields will help me (and others who are using ff2mpv) get the context needed to help you with your problem.

**Comment by woodruffw** [comment]
Closing due to lack of information.
