### ISSUE TITLE
Selecting resolution on YouTube (and possibly other sites)

### ISSUE THREAD

**Issue by bagnacauda** [woodruffw/ff2mpv#54]
**Is your feature request related to a problem? Please describe.**
Since this extension is very useful for those of us running on older machines, it would be nice to be able to limit (or select) a resolution, to avoid watching 4k videos on a Thinkpad T61.

**Describe the solution you'd like**
Be able to get a list of the resolution available, or at least be able to limit the resolution to a maximum.

**Describe alternatives you've considered**
Implement a preferences system in the extension page and sending the settings to the native client via native messaging, or as an alternative a config file read by the python script. I don't know which solution is the best one, but for sure the first one gives you more flexibility on what you can do.

**Additional context**

**Comment by bagnacauda** [comment]
Forgot to mention a pretty important thing, on YouTube. *facepalm*
It should be easy to do since mpv has the hook with youtube-dl.

**Comment by woodruffw** [comment]
Please refer to this comment: https://github.com/woodruffw/ff2mpv/issues/23#issuecomment-830821656

The TL;DR is that ff2mpv is a dumb extension that forwards URLs directly to MPV, which then proxies them to `youtube-dl` for actual retrieval. It doesn't do any configuration of its own -- if you want non-default resolution settings, you should configure MPV and/or `youtube-dl` directly to prioritize different resolutions during retrieval.

**Comment by woodruffw** [comment]
Something that I would consider: we could add a flag to the native client such that `ff2mpv` always requests the "ff2mpv" profile from MPV, which would then give users a little bit more granularity in their MPC config. I'm more than happy to accept a PR that does that!
