### ISSUE TITLE
ExtensionError: No such native application ff2mpv

### ISSUE THREAD

**Issue by fromtheeast710** [woodruffw/ff2mpv#58]
## Describe the bug

ff2mpv doesn't play video when use librewolf (a fork of firefox) but in the browser console, it says
`ExtensionError: No such native application ff2mpv`
with message
`Error: Attempt to postMessage on disconnected port`

## Reproduction steps

1. Install librewolf-bin
2. Install ff2mpv following the instructions
3. Use ff2mpv

## Expected behavior

The video is played in mpv

## Platform information

 - OS information: Aritx Linux
 - Firefox version: LibreWolf 91.0.1
 - MPV version: mpv 0.33.1-dirty
 - youtube-dl version: 2021.06.06

## Additional context (optional)

At first, install.sh could not detect ~/.mozilla so I have to make it manually, the installation was successful. My mpv.conf is
`[extension.webm]
loop-file=inf`

**Comment by fromtheeast710** [comment]
I tested this on a fresh install of firefox and it works perfectly, so the problem must be that I'm using librewolf.

**Comment by woodruffw** [comment]
Yeah, I have no idea whether this extension will work on any of the Firefox forks.

If you do manage to get it working, feel free to update the wiki with the steps you took. Others might find it useful, even though it won't be an officially supported configuration.

**Comment by fromtheeast710** [comment]
@woodruffw Yes, I was able to get it working simply by executing `cp -r .mozilla/native-messaging-hosts/ .librewolf/`

**Comment by fromtheeast710** [comment]
Done, even though I don't think there's enough to justify a wiki page.

**Comment by woodruffw** [comment]
Thanks. Yeah, it's a tiny case, but it means that I can link there (and tell people to expound on it) as/if issues arise.
