### ISSUE TITLE
ff2mpv not working on librewolf

### ISSUE THREAD

**Issue by butter2474** [woodruffw/ff2mpv#61]
## Describe the bug
I press play in MPV and it works in firefox but if I try the same in librewolf it does nothing.

## Reproduction steps

1. Go to 'youtube.com'
2. Click on 'play in MPV'
3. Wait.
4.Video plays (firefox), video never plays (librewolf)

## Expected behavior
plays video in MPV

## Platform information

 - OS information: Pop!_OS 21.04
 - Firefox version: librewolf 92.0.1
 - MPV version: newest (at the time of writing)
 - youtube-dl version: yt-dlp

## Additional context (optional)
I followed every step on the wiki for linux and librewolf and ran "cp -r .mozilla/native-messaging-hosts/ .librewolf/" but it still doesn't work on librewolf.

**Comment by pm4rcin** [comment]
Take a look at [that package](https://aur.archlinux.org/packages/ff2mpv-native-messaging-host-librewolf-git/). It works flawlessly for me. It's probably easy to port it to Ubuntu based distros.

**Comment by woodruffw** [comment]
Closing as stale, since other people seem to be using ff2mpv on Librewolf without issues.
