### ISSUE TITLE
[Request] Ability to set or change the mnemonics shortcut on right click

### ISSUE THREAD

**Issue by benyaminl** [woodruffw/ff2mpv#64]
**Is your feature request related to a problem? Please describe.**
Hello, I'm a new user here, and I see that "w" char is used as mnemonics on right click, I've container tabs and the container tabs use "w" char too, is there anyway to change the shortcut to something else on the fly or option to set to another character?

**Describe the solution you'd like**
If possible set to another char with option to fallback to "w"

**Describe alternatives you've considered**
Nothing, probably I will fork it and make my private addons with "v" as mnemonics

**Additional context**
See the screenshoot
![image](https://user-images.githubusercontent.com/2817332/139648428-278ba282-b2ef-4f0d-9dd4-c0f68403381d.png)

**Comment by woodruffw** [comment]
I'm not opposed to changing the mnemonic to `v` (I don't remember off the top of my head why it's `W`). Feel free to open a PR that does that.

**Comment by benyaminl** [comment]
@woodruffw but is it okay to add storage permission for saving and edit the shortcut? I mean some people will freak out. Or just change it to "V" *but it won't solve the problem in the future when it went to problem with other linux distro or MacOS, as I use it on windows

**Comment by woodruffw** [comment]
> but is it okay to add storage permission for saving and edit the shortcut? I mean some people will freak out. Or just change it to "V" *but it won't solve the problem in the future when it went to problem with other linux distro or MacOS, as I use it on windows

I'd prefer to not add that permission: this extension has lasted a remarkably long time without needing any browser-side configuration state, and I'd like to keep it that way!

If you're worried about breaking Linux and macOS functionality (which I appreciate you bringing up), we can consider using the [`runtime.getPlatformInfo`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getPlatformInfo) to only change the behavior here for Windows. Other platforms can keep the current mnemonic shortcut.

**Comment by benyaminl** [comment]
@woodruffw I think I can guess why you're using W on your mnemonics, as on saving videos, the mnemonics is "v", so w is best one. hmm.. can we make 2 different right click for video and for link?

**Comment by Dimithrandir** [comment]
'W' was chosen because it was the only vacant key by default above the left side of the home row, making it the easiest to reach. 'V' would've been ideal, but it's is used for "Save Video As..." and "Save Image As...". Other available keys on Linux are 'Z' and 'X', not sure about other platforms, but they could be taken by other extensions too.

As Firefox Containers is a very popular extension and many other ff2mpv users probably use it, we could add the hotkey only if the containers addon is not installed, similarly to #65, using `management.get()`, but this would require the management API permission, which is not preferable.

**Comment by woodruffw** [comment]
Merged with #66. I'll cut a release in a bit. Thanks for bearing with me.

**Comment by woodruffw** [comment]
Cut with 3.9.0, which should be available on AMO shortly.

**Comment by benyaminl** [comment]
@woodruffw Hello, Sorry for not reaching back. When I write &V as if, it's intended because now on windows the mnemonics become double like this

![image](https://user-images.githubusercontent.com/2817332/143687569-e471e9b1-325a-4630-9a10-f656417a6d0c.png)

Because it's the same character, as I know it's also the same as on RHEL, well this is only small cosmetic issue. if next release is rolled out, will this possible to be fixed? Thank you

**Comment by woodruffw** [comment]
Yeah, I'll fix that with the next release. Thanks for letting me know.

**Comment by woodruffw** [comment]
Released with 3.9.1, should be on AMO soon.

**Comment by benyaminl** [comment]
That should be fine. I think on next release with other patch will be
better. 👍

it's just small minor fixes. 🙏




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by benyaminl** [comment]
@woodruffw Thank you sir. The new patch already pushed to user 🙏
![image](https://user-images.githubusercontent.com/2817332/143769103-7a4de4af-a52a-494e-a3ff-3d6fe222e550.png)

**Comment by patjldeiM0IP** [comment]
Sorry to reopen this but is there any reason v is only used in windows, not linux? Linux also uses W for "Open link in new container".

**Comment by woodruffw** [comment]
If I remember correctly, there was a separate conflict with `v` on Linux. The original mnemonic functionality with `W` predated container support in Firefox, which is why it was chosen. But we can move that around, if there’s a better candidate now.

**Comment by benyaminl** [comment]
> If I remember correctly, there was a separate conflict with `v` on Linux. The original mnemonic functionality with `W` predated container support in Firefox, which is why it was chosen. But we can move that around, if there’s a better candidate now. Sent from mobile. Please excuse my brevity.
> […](#)
> On Dec 24, 2021, at 5:27 PM, patjldeiM0IP ***@***.***> wrote: ﻿ Sorry to reopen this but is there any reason v is only used in windows, not linux? Linux also uses W for "Open link in new container". — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

Can we make or check if other addons is activated, then we change the shortcut key? I mean it will create new permission, or we can make settings page like @Dimithrandir said. Hmm..

**Comment by woodruffw** [comment]
I'm still 👎 on requiring additional permissions or introducing a settings page.

It's not ideal, but it looks like the current mnemonics function just fine with two keyboard inputs instead of just one (i.e., pressing `w` twice instead of once). Is that a dealbreaker for anyone?

**Comment by patjldeiM0IP** [comment]
It's actually three keyboard inputs: `W`, `W`, `Enter`, which is cumbersome if using the mouse with your right hand - you have to move your left hand from the home row position to hit the enter key. Even so, it's not a dealbreaker.
