### ISSUE TITLE
how to add yt-dlp since yt-dl is dead

### ISSUE THREAD

**Issue by G2G2G2G** [woodruffw/ff2mpv#67]
https://github.com/woodruffw/ff2mpv/blob/master/ff2mpv.py#L15

is this the proper way?
```
    args = ["mpv", "--script-opts=ytdl_hook-ytdl_path=yt-dlp", "--no-terminal", "--", url]
```
also what is the last "--" in there before url?
thanks

**Comment by Feanor1397** [comment]
Here is how I replaced original youtube-dl with yt-lpp
Create file named /usr/bin/youtube-dl, and paste this short script in it

```
#!/bin/sh
/usr/bin/yt-dlp --compat-options youtube-dl "$@"

```

And thats it. everything will work like with original youtube-dl

**Comment by woodruffw** [comment]
All `ff2mpv` does is call MPV; we're completely agnostic to *how* MPV decides to handle whatever URL it gets passed (it could call `youtube-dl`, or `yt-dlp`, or fetch the file itself, or anything else).

The additional flag you added looks correct. However, just in case we change the native client in the future, the best place to put that is in one of your MPV configs. 

@Feanor1397's solution also works, and that's how I do it locally.
