### ISSUE TITLE
New functionality ― Add video to a playlist.

### ISSUE THREAD

**Issue by icaro-meneses** [woodruffw/ff2mpv#74]
**Is your feature request related to a problem? Please describe.**
When I'm watching some video through ffmpv Firefox Extension, for example, some series of tutorials, I can't add multiple videos to a playlist. In this case, I already have an instance of mpv open, and I can't add another video in the queue.

**Describe the solution you'd like**
It would be interesting if you had an option that would add a video to a playlist.

**Describe alternatives you've considered**
Create another option in the default context menu (when we right-click on the desired video), to add the video to a playlist.

**Additional context**
As an example case: I find a video of a programming tutorial, then I right click to play with mpv, then an mpv window opens. After I find another video, and with the other option to "add to playlist", the video goes to mpv playback queue, in the window that was previously opened, allowing me to go forward or backward in the playlist.
I hope I have been clear in the details, I also hope that this addition of functionality, helps to improve the usability of the project.

**Comment by woodruffw** [comment]
> When I'm watching some video through ffmpv Firefox Extension, for example, some series of tutorials, I can't add multiple videos to a playlist. In this case, I already have an instance of mpv open, and I can't add another video in the queue.

ff2mpv should already support this: `youtube-dl` understands playlists on YouTube (and other services), and can forward that playlist metadata to MPV.

Try adding the following to your MPV config:

```
ytdl-raw-options=yes-playlist=
```

(That last `=` is important; don't remove it)

**Comment by woodruffw** [comment]
More generally: the development policy on ff2mpv is to never duplicate functionality that's already present in MPV or `youtube-dl`. If we can get it working via MPV's config, then that'll be the recommended approach.

**Comment by icaro-meneses** [comment]
Oh... That's very good! I didn't know that possibility. I apologize for the inconvenience. Thank you very much for the guidance!

**Comment by woodruffw** [comment]
It's not an inconvenience! I appreciate you creating the issue and describing the problem you've had, because other users will almost certainly have the same problem. When they do, I can link them here :slightly_smiling_face: 

So again: thank you, and don't be hesitant to ask questions or raise potential features in the future. I'm just a stickler for keeping this extension as lean and mean as it can be.
