### ISSUE TITLE
Extension doesn't work on YouTube in Chrome

### ISSUE THREAD

**Issue by boopnbop** [woodruffw/ff2mpv#85]
## Describe the bug

MPV is not opened when I try to use the extension on YouTube.

## Reproduction steps

When I click on the extension in the extension bar, or click "Play in MPV" on a thumbnail, nothing at all happens.

## Expected behavior

I expected mpv to open showing the video.

## Screenshots

![image](https://user-images.githubusercontent.com/74942715/175489459-50562c3c-4d85-4612-8002-ccd6f3a63551.png)
![image](https://user-images.githubusercontent.com/74942715/175490053-04dc3780-3505-4fc2-a913-ed3b2e80900d.png)
![image](https://user-images.githubusercontent.com/74942715/175492147-dceb67c7-c801-435b-b0b6-e992cf8acfa2.png)
![image](https://user-images.githubusercontent.com/74942715/175492760-026e1082-40e5-4c4e-9d1e-d6aa92d9c9c5.png)
![image](https://user-images.githubusercontent.com/74942715/175493830-d2575d65-f738-4ef1-9d71-f20e60fcab39.png)
![image](https://user-images.githubusercontent.com/74942715/175646062-374ffe6b-fe40-40eb-b7bf-4bede3290e7a.png)
![image](https://user-images.githubusercontent.com/74942715/175646107-bb46a123-a04c-4fe7-9e8c-8ac40cb7d1e3.png)
![image](https://user-images.githubusercontent.com/74942715/175646223-26df8ce9-3009-43c1-93a4-0794428b2281.png)

## Platform information

 - OS information: Windows 10
 - Google Chrome version: 102.0.5005.115
 - MPV version: 0.34.0
 - yt-dlp version: 2022.06.22.1

## Additional context

Doing "mpv [insert link]" in the command prompt works fine, but this extension has not worked a single time. I also tried this extension quickly on Vimeo and it did not work either, but I haven't tried my chances on Vimeo many times or on any other streaming services, simply because I'm just not interested. I messed around with the troubleshooting methods but I still can't get it to work. Have I done something wrong?

I installed the extension from the Chrome web store, and the code from the zip file at the top of the github page. I don't remember where I installed any of my programs, but I'm sure I could figure that out if it's necessary. Thank you in advance! Sorry, I'm not very technologically literate ig haha.

**Comment by woodruffw** [comment]
Thanks for the report @boopnbop.

I don't directly maintain this extension for Windows, but as a guess: it looks like the JSON in your `ff2mpv-windows.json` file is slightly malformed.

In particular, you're missing a closing `]` after the line that contains the `chrome-extension://` URL. It should probably look something like this:

```json
{
    "name": "ff2mpv",
    "description": "ff2mpv's native manifest",
    "path": "ff2mpv.bat",
    "type": "stdio",
    "allowed_extensions": ["chrome-extension://ephjcajbkgplkjmelpglennepbpmdpjg/"]
}
```

Try copying and pasting that into your file, and see if it works.

**Comment by woodruffw** [comment]
CC @DanSM-5, in case you have any theories.

**Comment by DanSM-5** [comment]
Just to confirm this is not an issue with the encoding, could you delete ff2mpv.bat (the one that says "Windows Batch file") and create a new file with the same name copying this as the content?

```
@echo off
call py -3 ff2mpv.py
```

**Comment by DanSM-5** [comment]
I noticed that you have `yt-dlp` in the same folder that mpv. If that's the case you don't need the extra line in the `mpv.conf` file. Could you try without that?

Another thing, could you check which version of python do you have?
Try `py --version` in powershell. If it doesn't work try `python` or `python3`.

**Comment by DanSM-5** [comment]
The video stopping is a feature of the extension. It stops the current video element if there is one.
The black box with the link is a behavior of Chrome. It will appear every time you hover a link.

Could you confirm which python command you use to check the version of python? It varies depending on how you installed python.

**Comment by DanSM-5** [comment]
@boopnbop I think I found the issue. The path in the registry key should be set in the `(Default)` key.

![image](https://user-images.githubusercontent.com/49035812/177021049-524c18f5-77e7-4984-890d-a354a296bde8.png)

In the screenshot I see it is set in a different key with the name of the path. It should be set in (Default).

**Comment by DanSM-5** [comment]
The entry in the registry is fine if you are using Google Chrome (Google -> Chrome). The entry under Chromium is for the Chromium browser which is a different browser.

The ff2mpv-windows.json has the key `"allowed_extensions"` that is for Firefox. For chromium browsers it should be `"allowed_origins"`.

```
{
  "name": "ff2mpv",
  "description": "ff2mpv's native manifest",
  "path": "ff2mpv.bat",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://ephjcajbkgplkjmelpglennepbpmdpjg/"
  ]
}
```

Hopefully this will work.
