### ISSUE TITLE
Wiki installation instructions inaccurate

### ISSUE THREAD

**Issue by noscript** [woodruffw/ff2mpv#9]
Both Linux and MacOS instructions are inaccurate.

https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Linux
https://github.com/woodruffw/ff2mpv/wiki/Installation-on-macOS

In step 1, the part about scrips being in `$PATH` is not needed as it doesn't affect anything. Native Messaging documentation for both [Chrome](https://developer.chrome.com/apps/nativeMessaging#native-messaging-host-location) and [Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_manifests) states that `path` attribute in messaging manifest on Linux and MacOS should be absolute path to executable.

**Comment by woodruffw** [comment]
Thanks, I've updated the pages.
