### ISSUE TITLE
add support for baka mplayer

### ISSUE THREAD

**Issue by 3flowin** [woodruffw/ff2mpv#91]
**Is your feature request related to a problem? Please describe.**
nope
**Describe the solution you'd like**
make so that the addon support baka mplayer

**Describe alternatives you've considered**
mpv, though i havent tried it since i dont want to learn fucking keybinds that i might forget

**Additional context**
a

**Comment by woodruffw** [comment]
This should be a patch to your local native client (you can just invoke whatever player you'd like instead of `mpv`). Check out the wiki for some examples of people doing that.
