### ISSUE TITLE
Doesn't work in Vivaldi browser

### ISSUE THREAD

**Issue by greqov** [woodruffw/ff2mpv#92]
**IMPORTANT: Please check the [Common problems](https://github.com/woodruffw/ff2mpv/wiki/Common-problems) page for debugging tips before submitting an issue. Duplicates of any information on that page will be closed.**

**IMPORTANT: Please fill out every section below. Bug reports with missing information will be
given a lower priority or closed outright.**

## Describe the bug

Nothing happens after clicking on 'Play in MPV(W)' context menu or after clicking on extension icon in Vivaldi browser. Works fine in Chromium.

## Reproduction steps

1. Open any youtube video.
2. Click on extension icon or pick 'Play with MPV(W)' in browser's context menu.

## Expected behavior

MPV opens up and starts playing selected video.

## Screenshots (optional)

..

## Platform information

 - OS information: Manjaro Linux 22.0.0
 - browser version: Vivaldi 5.6.2867.58 stable
 - MPV version: mpv 0.35.0
 - youtube-dl version: yt-dlp 2022.11.11

## Additional context (optional)

All works fine in Chromium. Tried these commands with no luck:
```
./install.sh custom-chromium $HOME/.config/chromium
./install.sh custom-chromium $HOME/.config/vivaldi
```

**Comment by woodruffw** [comment]
Thanks for the report.

Vivaldi isn't an officially supported browser so I can't guarantee any degree of support here (even if you get it working), but I'll leave this open in case other users have experience with it and can share some tips.

(If you do happen to get it working, please modify/update the wiki to include any steps you needed!)

**Comment by DanSM-5** [comment]
Looking at [this](https://forum.vivaldi.net/topic/48659/location-of-native-messaging-hosts-on-linux) post in vivaldi's forum I see that the path could be one of the following:
- ~/.config/vivaldi/NativeMessagingHosts
- ~/.config/vivaldi-snapshot/NativeMessagingHosts
You tried with the first one. Maybe you can try with the other one (`$HOME/.config/vivaldi-snapshot`).

**Comment by greqov** [comment]
I saw that post. Unfortunately, it doesn't work for me.
