### ISSUE TITLE
FreeBSD patch

### ISSUE THREAD

**Issue by BornTactical** [woodruffw/ff2mpv#93]
Essentially the same as Linux. Will probably work with other BSD unames:

```
From 4d864478ebf10f806c557309d8992c0524076ac4 Mon Sep 17 00:00:00 2001
From: BornTactical <BornTactical@github.com>
Date: Tue, 17 Jan 2023 20:46:16 -0600
Subject: [PATCH] FreeBSD patch

---
 install.sh | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/install.sh b/install.sh
index dd3674a..f34b00d 100755
--- a/install.sh
+++ b/install.sh
@@ -83,6 +83,10 @@ Linux*)
   BROWSER_DEST="$linux_path"
   JSON_DEST="$BROWSER_DEST/$LINUX_NMH_DIR"
   ;;
+FreeBSD*)
+  BROWSER_DEST="$linux_path"
+  JSON_DEST="$BROWSER_DEST/$LINUX_NMH_DIR"
+  ;;
 Darwin*)
   BROWSER_DEST="$mac_path"
   JSON_DEST="$BROWSER_DEST/NativeMessagingHosts"
-- 
2.39.0
```

**Comment by woodruffw** [comment]
Thanks for the patch. Is there a reason you didn't do it through a PR? 

(I'm perfectly happy to `git apply` it instead, just curious!)

**Comment by woodruffw** [comment]
1f6cfc4..371d8df

Thanks again!

**Comment by BornTactical** [comment]
> Thanks for the patch. Is there a reason you didn't do it through a PR?
> 
> (I'm perfectly happy to `git apply` it instead, just curious!)

Some people consider pull requests rude. I don't care personally but I'd prefer to run any changes by the maintainer in a more informal way. Thanks for the apply!

**Comment by woodruffw** [comment]
No problem! And PRs are fine in the future -- I don't consider them rude at all!
