### ISSUE TITLE
[Question] How should I set the args syntax if I want to use the MPV variable?

### ISSUE THREAD

**Issue by sun95n** [woodruffw/ff2mpv#97]
Hi, I am using the [umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv) script to use the same window when opening many videos. The problem is that, if I want to add custom options, I have to edit line [84](https://github.com/mpv-player/mpv/blob/022790a2b49e4d21cb803842cb54958cca9c732e/TOOLS/umpv#L84) of this script or use the [MPV variable](https://github.com/mpv-player/mpv/blob/022790a2b49e4d21cb803842cb54958cca9c732e/TOOLS/umpv#L22-L26). The latter is what I want to achieve in `ff2mpv.py` but unfortunately no video opens.

I used the first method to add the `--ontop` flag. It works well.
```
args = ["umpv", url]
```
The second method works fine when run in a terminal, but not when editing `ff2mpv.py` Am I setting the syntax right?
```
args = ["env MPV="mpv --ontop" umpv", url]
```

**Comment by Roman2K** [comment]
Hi @sun95n,

Your second method wouldn't work because you're trying to pass a whole shell line as the executable path (also invalid syntax due to improper quoting).

I think the array should look like this:

```
args = ["env", "MPV=mpv --ontop", "umpv", url]
```

Does that work?

**Comment by woodruffw** [comment]
Glad to hear it; thanks @Roman2K for answering!
